// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	v1 "github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CreateCertificate provides a mock function for the type MockUsecase
func (_mock *MockUsecase) CreateCertificate(ctx context.Context, certificate *v1.Certificate) (*v1.Certificate, error) {
	ret := _mock.Called(ctx, certificate)

	if len(ret) == 0 {
		panic("no return value specified for CreateCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Certificate) (*v1.Certificate, error)); ok {
		return returnFunc(ctx, certificate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Certificate) *v1.Certificate); ok {
		r0 = returnFunc(ctx, certificate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.Certificate) error); ok {
		r1 = returnFunc(ctx, certificate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_CreateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCertificate'
type MockUsecase_CreateCertificate_Call struct {
	*mock.Call
}

// CreateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - certificate *v1.Certificate
func (_e *MockUsecase_Expecter) CreateCertificate(ctx interface{}, certificate interface{}) *MockUsecase_CreateCertificate_Call {
	return &MockUsecase_CreateCertificate_Call{Call: _e.mock.On("CreateCertificate", ctx, certificate)}
}

func (_c *MockUsecase_CreateCertificate_Call) Run(run func(ctx context.Context, certificate *v1.Certificate)) *MockUsecase_CreateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Certificate
		if args[1] != nil {
			arg1 = args[1].(*v1.Certificate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_CreateCertificate_Call) Return(certificate *v1.Certificate, err error) *MockUsecase_CreateCertificate_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *MockUsecase_CreateCertificate_Call) RunAndReturn(run func(ctx context.Context, certificate *v1.Certificate) (*v1.Certificate, error)) *MockUsecase_CreateCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCertificate provides a mock function for the type MockUsecase
func (_mock *MockUsecase) DeleteCertificate(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCertificate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_DeleteCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCertificate'
type MockUsecase_DeleteCertificate_Call struct {
	*mock.Call
}

// DeleteCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUsecase_Expecter) DeleteCertificate(ctx interface{}, name interface{}) *MockUsecase_DeleteCertificate_Call {
	return &MockUsecase_DeleteCertificate_Call{Call: _e.mock.On("DeleteCertificate", ctx, name)}
}

func (_c *MockUsecase_DeleteCertificate_Call) Run(run func(ctx context.Context, name string)) *MockUsecase_DeleteCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_DeleteCertificate_Call) Return(err error) *MockUsecase_DeleteCertificate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_DeleteCertificate_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockUsecase_DeleteCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCertificate provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetCertificate(ctx context.Context, name string) (*v1.Certificate, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.Certificate, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.Certificate); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCertificate'
type MockUsecase_GetCertificate_Call struct {
	*mock.Call
}

// GetCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUsecase_Expecter) GetCertificate(ctx interface{}, name interface{}) *MockUsecase_GetCertificate_Call {
	return &MockUsecase_GetCertificate_Call{Call: _e.mock.On("GetCertificate", ctx, name)}
}

func (_c *MockUsecase_GetCertificate_Call) Run(run func(ctx context.Context, name string)) *MockUsecase_GetCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetCertificate_Call) Return(certificate *v1.Certificate, err error) *MockUsecase_GetCertificate_Call {
	_c.Call.Return(certificate, err)
	return _c
}

func (_c *MockUsecase_GetCertificate_Call) RunAndReturn(run func(ctx context.Context, name string) (*v1.Certificate, error)) *MockUsecase_GetCertificate_Call {
	_c.Call.Return(run)
	return _c
}

// ListCertificates provides a mock function for the type MockUsecase
func (_mock *MockUsecase) ListCertificates(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Certificate], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListCertificates")
	}

	var r0 *v1.ListResponse[v1.Certificate]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*v1.ListResponse[v1.Certificate], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.Certificate]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Certificate])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_ListCertificates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCertificates'
type MockUsecase_ListCertificates_Call struct {
	*mock.Call
}

// ListCertificates is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockUsecase_Expecter) ListCertificates(ctx interface{}, options interface{}) *MockUsecase_ListCertificates_Call {
	return &MockUsecase_ListCertificates_Call{Call: _e.mock.On("ListCertificates", ctx, options)}
}

func (_c *MockUsecase_ListCertificates_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockUsecase_ListCertificates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_ListCertificates_Call) Return(v *v1.ListResponse[v1.Certificate], err error) *MockUsecase_ListCertificates_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUsecase_ListCertificates_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Certificate], error)) *MockUsecase_ListCertificates_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCertificate provides a mock function for the type MockUsecase
func (_mock *MockUsecase) UpdateCertificate(ctx context.Context, name string, certificate *v1.Certificate) (*v1.Certificate, error) {
	ret := _mock.Called(ctx, name, certificate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCertificate")
	}

	var r0 *v1.Certificate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.Certificate) (*v1.Certificate, error)); ok {
		return returnFunc(ctx, name, certificate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.Certificate) *v1.Certificate); ok {
		r0 = returnFunc(ctx, name, certificate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Certificate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v1.Certificate) error); ok {
		r1 = returnFunc(ctx, name, certificate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_UpdateCertificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCertificate'
type MockUsecase_UpdateCertificate_Call struct {
	*mock.Call
}

// UpdateCertificate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - certificate *v1.Certificate
func (_e *MockUsecase_Expecter) UpdateCertificate(ctx interface{}, name interface{}, certificate interface{}) *MockUsecase_UpdateCertificate_Call {
	return &MockUsecase_UpdateCertificate_Call{Call: _e.mock.On("UpdateCertificate", ctx, name, certificate)}
}

func (_c *MockUsecase_UpdateCertificate_Call) Run(run func(ctx context.Context, name string, certificate *v1.Certificate)) *MockUsecase_UpdateCertificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.Certificate
		if args[2] != nil {
			arg2 = args[2].(*v1.Certificate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_UpdateCertificate_Call) Return(certificate1 *v1.Certificate, err error) *MockUsecase_UpdateCertificate_Call {
	_c.Call.Return(certificate1, err)
	return _c
}

func (_c *MockUsecase_UpdateCertificate_Call) RunAndReturn(run func(ctx context.Context, name string, certificate *v1.Certificate) (*v1.Certificate, error)) *MockUsecase_UpdateCertificate_Call {
	_c.Call.Return(run)
	return _c
}
