version: "2"
linters:
  default: all
  disable:
    - wsl
  exclusions:
    paths:
      - "pkg/apiserver/docs/docs.go" # Generated file for Swagger documentation
    rules:
      - path: _test\.go
        linters:
          - funlen
          - varnamelen
          - exhaustruct
  settings:
    gomoddirectives:
      replace-local: true
      replace-allow-list:
        - go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/v2/mongo/otelmongo
    funlen:
      ignore-comments: true
    cyclop:
      max-complexity: 15 # default: 10, but too strict
    varnamelen:
      ignore-type-assert-ok: true # default: false, but it's common in Go
      ignore-map-index-ok: true # default: false, but it's common in Go
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
    ireturn:
      allow:
        - generic
        - error
        - stdlib
        - empty
        - anon
        - Option$
        - Provider$ # Provider is commonly used
        - '.+/management\.HTTPHandler$'
        - '.+/trace\.Sampler$'
    depguard:
      rules:
        main:
          files:
            - "!**/*_test.go" # Exclude test files
            - "!**/testutil/*" # Exclude testutil package
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            # Basic Frameworks
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/spf13/afero
            - go.uber.org/fx
            - github.com/gin-gonic/gin
            # Basic Libraries
            - github.com/google/uuid
            # OpAMP
            - github.com/open-telemetry/opamp-go/protobufs
            - github.com/open-telemetry/opamp-go/server
            # Database
            - go.mongodb.org/mongo-driver/v2/mongo
            - go.mongodb.org/mongo-driver/v2/bson
            - go.mongodb.org/mongo-driver/v2/event
            - go.opentelemetry.io/contrib/instrumentation/go.mongodb.org/mongo-driver/v2/mongo/otelmongo
            # Utils
            - github.com/samber/lo
            - k8s.io/utils/clock
            - github.com/go-resty/resty/v2
            - gopkg.in/yaml.v3
            - github.com/puzpuzpuz/xsync/v3
            - github.com/spf13/pflag
            # authentication
            - golang.org/x/oauth2
            - golang.org/x/oauth2/github
            - github.com/golang-jwt/jwt/v5
            - github.com/google/go-github/v72/github
            # documentation
            - github.com/swaggo/files
            - github.com/swaggo/gin-swagger
            # observability
            - github.com/samber/slog-gin
            - go.opentelemetry.io/otel
            - go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin
            - github.com/prometheus/client_golang/prometheus
            - go.opentelemetry.io/contrib/instrumentation/runtime
          deny:
            - pkg: github.com/minuk-dev/opampcommander/pkg/testutil
              desc: Do not use testutil in production code
        internal:
          files:
            - "internal/**"
          deny:
            - pkg: go.uber.org/fx
              desc: Do not use fx in internal packages.
        test:
          files:
            - "**/*_test.go"
            - "**/testutil/*"
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/spf13/afero
            - github.com/gin-gonic/gin
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/mock
            - github.com/google/uuid
            - github.com/tidwall/gjson
            - gotest.tools/icmd
            - go.uber.org/goleak
            - go.mongodb.org/mongo-driver/v2/mongo
            - go.mongodb.org/mongo-driver/v2/bson
            - github.com/testcontainers/testcontainers-go
            - github.com/testcontainers/testcontainers-go/modules/mongodb
            - github.com/testcontainers/testcontainers-go/wait
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/minuk-dev/opampcommander)
