version: "2"
linters:
  default: all
  settings:
    varnamelen:
      ignore-type-assert-ok: true # default: false
      ignore-map-index-ok: true # default: false
    ireturn:
      allow:
        - generic
        - error
        - stdlib
        - empty
        - anon
    depguard:
      rules:
        main:
          files:
            - "!**/*_test.go" # Exclude test files
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/gin-gonic/gin
            - github.com/samber/slog-gin
            - github.com/samber/lo
            - github.com/spf13/cobra
            - go.uber.org/fx
            - github.com/google/uuid
            - github.com/open-telemetry/opamp-go/protobufs
            - k8s.io/utils/clock
            - github.com/open-telemetry/opamp-go/server
            - go.etcd.io/etcd/client/v3
            - github.com/go-resty/resty/v2
            - gopkg.in/yaml.v3
            - github.com/puzpuzpuz/xsync/v3
          deny:
            - pkg: github.com/minuk-dev/opampcommander/pkg/testutil
              desc: Do not use testutil in production code
        test:
          files:
            - "**/*_test.go"
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/gin-gonic/gin
            - github.com/stretchr/testify/assert

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/minuk-dev/opampcommander)
