version: "2"
linters:
  default: all

  settings:

    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/gin-gonic/gin
            - github.com/samber/slog-gin
            - github.com/samber/lo
            - github.com/spf13/cobra
            - go.uber.org/fx
            - github.com/google/uuid
            - github.com/open-telemetry/opamp-go/protobufs
            - k8s.io/utils/clock
            - github.com/open-telemetry/opamp-go/server
            - go.etcd.io/etcd/client/v3
            - github.com/go-resty/resty/v2
            - gopkg.in/yaml.v3
            - github.com/puzpuzpuz/xsync/v3

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/minuk-dev/opampcommander)
