version: "2"
linters:
  default: all
  settings:
    cyclop:
      max-complexity: 15 # default: 10
    varnamelen:
      ignore-type-assert-ok: true # default: false
      ignore-map-index-ok: true # default: false
    ireturn:
      allow:
        - generic
        - error
        - stdlib
        - empty
        - anon
    depguard:
      rules:
        main:
          files:
            - "!**/*_test.go" # Exclude test files
            - "!**/testutil/*" # Exclude testutil package
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/gin-gonic/gin
            - github.com/samber/slog-gin
            - github.com/samber/lo
            - github.com/spf13/cobra
            - github.com/spf13/viper
            - github.com/spf13/afero
            - go.uber.org/fx
            - github.com/google/uuid
            - github.com/open-telemetry/opamp-go/protobufs
            - k8s.io/utils/clock
            - github.com/open-telemetry/opamp-go/server
            - go.etcd.io/etcd/client/v3
            - github.com/go-resty/resty/v2
            - gopkg.in/yaml.v3
            - github.com/puzpuzpuz/xsync/v3
            - golang.org/x/oauth2
            - golang.org/x/oauth2/github
            - github.com/golang-jwt/jwt/v5
            - github.com/google/go-github/v72/github
          deny:
            - pkg: github.com/minuk-dev/opampcommander/pkg/testutil
              desc: Do not use testutil in production code
        test:
          files:
            - "**/*_test.go"
            - "**/testutil/*"
          allow:
            - $gostd
            - github.com/minuk-dev/opampcommander
            - github.com/spf13/afero
            - github.com/gin-gonic/gin
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/mock
            - github.com/google/uuid
            - github.com/tidwall/gjson
            - gotest.tools/icmd
            - go.uber.org/goleak
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/minuk-dev/opampcommander)
