linters:
  enable-all: true
  disable:
    # The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    - exportloopref

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/minuk-dev/opampcommander)

  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/minuk-dev/opampcommander
          - github.com/gin-gonic/gin
          - github.com/samber/slog-gin
          - github.com/samber/lo
          - github.com/spf13/cobra
          - github.com/gorilla/websocket
          - github.com/open-telemetry/opamp-go/protobufs
          - github.com/google/uuid
          - github.com/puzpuzpuz/xsync/v3
          - github.com/go-resty/resty/v2
          - github.com/open-telemetry/opamp-go/types
          - github.com/open-telemetry/opamp-go/server
          - k8s.io/utils/clock
