package remoteconfigschema

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"time"

	"golang.org/x/mod/semver"

	v1 "github.com/minuk-dev/opampcommander/api/v1"
)

// DefaultSchemaLocation is the schema registry read when none is given:
// github.com/minuk-dev/otelcol-config-schemas, a data repository of per-release
// component schemas generated by tools/schemagen in
// github.com/minuk-dev/otelcol-config-lint, from each release's upstream
// metadata.yaml, its components' Config structs, and the config.schema.yaml the
// collector publishes from v0.150.0 on. It is the registry otelcol-config-lint reads,
// so a config linted locally is checked against the same catalog the server holds.
const DefaultSchemaLocation = "https://raw.githubusercontent.com/minuk-dev/otelcol-config-schemas/main"

// VersionLatest selects the newest version a distribution has a schema for.
const VersionLatest = "latest"

// registryTimeout bounds a single registry read.
const registryTimeout = 60 * time.Second

var (
	// ErrNoSchemaForDistribution is returned when the registry has no schema for the
	// requested distribution.
	ErrNoSchemaForDistribution = errors.New("registry has no schema for distribution")
	// ErrRegistryStatus is returned when the registry answers with a non-OK status.
	ErrRegistryStatus = errors.New("unexpected registry response")
)

// registryIndex is the registry's index.json: the releases each distribution has a
// schema for.
type registryIndex struct {
	Distributions map[string][]string `json:"distributions"`
}

// registryDoc is one registry schema file. Its component and field vocabulary is the
// one the API model uses, so the components decode straight into v1 types; only the
// class keys differ ("receiver" here, "receivers" in a collector config).
type registryDoc struct {
	CollectorVersion string                             `json:"collectorVersion"`
	Distribution     string                             `json:"distribution"`
	Components       map[string]map[string]v1.Component `json:"components"`
}

// fetchFromRegistry reads the schema for distribution at version from location, which
// is either a base URL or a local checkout of the registry. A version of "latest" (or
// empty) resolves to the newest release the registry indexes for that distribution.
func fetchFromRegistry(ctx context.Context, location, distribution, version string) (*collected, error) {
	if version == "" || version == VersionLatest {
		resolved, err := latestRegistryVersion(ctx, location, distribution)
		if err != nil {
			return nil, err
		}

		version = resolved
	}

	data, err := readRegistryFile(ctx, location, distribution+"/"+withVersionPrefix(version)+".json")
	if err != nil {
		return nil, err
	}

	var doc registryDoc

	err = json.Unmarshal(data, &doc)
	if err != nil {
		return nil, fmt.Errorf("decode schema for %s %s: %w", distribution, version, err)
	}

	return &collected{
		Command:    "",
		Version:    strings.TrimPrefix(doc.CollectorVersion, "v"),
		Components: registryCatalog(doc.Components),
	}, nil
}

// latestRegistryVersion reads index.json and returns the newest version the registry
// has for distribution.
func latestRegistryVersion(ctx context.Context, location, distribution string) (string, error) {
	data, err := readRegistryFile(ctx, location, "index.json")
	if err != nil {
		return "", err
	}

	var index registryIndex

	err = json.Unmarshal(data, &index)
	if err != nil {
		return "", fmt.Errorf("decode registry index: %w", err)
	}

	versions := index.Distributions[distribution]
	if len(versions) == 0 {
		return "", fmt.Errorf("%w: %q (indexed: %s)",
			ErrNoSchemaForDistribution, distribution, strings.Join(indexedDistributions(index), ", "))
	}

	return slices.MaxFunc(versions, func(left, right string) int {
		return semver.Compare(withVersionPrefix(left), withVersionPrefix(right))
	}), nil
}

func indexedDistributions(index registryIndex) []string {
	names := make([]string, 0, len(index.Distributions))
	for name := range index.Distributions {
		names = append(names, name)
	}

	slices.Sort(names)

	return names
}

// registryCatalog converts a registry catalog to the schema's own vocabulary: its
// class keys are singular ("receiver"), while a schema keys components by the section
// they appear under in a collector config ("receivers").
func registryCatalog(components map[string]map[string]v1.Component) v1.ComponentCatalog {
	catalog := make(v1.ComponentCatalog, len(components))
	for class, byName := range components {
		catalog[pluralClass(class)] = byName
	}

	return catalog
}

// pluralClass turns a registry class key into a collector config section name. Class
// keys are open-ended, so one that is already plural is left as is.
func pluralClass(class string) string {
	if strings.HasSuffix(class, "s") {
		return class
	}

	return class + "s"
}

// readRegistryFile reads path relative to location, which is a base URL when it parses
// as one and a local directory otherwise.
func readRegistryFile(ctx context.Context, location, path string) ([]byte, error) {
	if isURL(location) {
		return readRegistryURL(ctx, strings.TrimSuffix(location, "/")+"/"+path)
	}

	full := filepath.Join(location, filepath.FromSlash(path))

	data, err := os.ReadFile(filepath.Clean(full))
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", full, err)
	}

	return data, nil
}

func readRegistryURL(ctx context.Context, rawURL string) ([]byte, error) {
	timeoutCtx, cancel := context.WithTimeout(ctx, registryTimeout)
	defer cancel()

	request, err := http.NewRequestWithContext(timeoutCtx, http.MethodGet, rawURL, nil)
	if err != nil {
		return nil, fmt.Errorf("build request for %q: %w", rawURL, err)
	}

	response, err := http.DefaultClient.Do(request)
	if err != nil {
		return nil, fmt.Errorf("get %q: %w", rawURL, err)
	}
	defer response.Body.Close() //nolint:errcheck // read-only body

	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%w: %s for %q", ErrRegistryStatus, response.Status, rawURL)
	}

	data, err := io.ReadAll(response.Body)
	if err != nil {
		return nil, fmt.Errorf("read %q: %w", rawURL, err)
	}

	return data, nil
}

func isURL(location string) bool {
	parsed, err := url.Parse(location)

	return err == nil && (parsed.Scheme == "http" || parsed.Scheme == "https")
}

// withVersionPrefix normalizes a collector version to the registry's "vX.Y.Z" form.
func withVersionPrefix(version string) string {
	if strings.HasPrefix(version, "v") {
		return version
	}

	return "v" + version
}

// stripDocs removes the documentation strings from a catalog, keeping only what
// validation needs. The pre-built schema library ships without them: they are most of
// the bytes and none of the checks.
func stripDocs(catalog v1.ComponentCatalog) {
	for _, byName := range catalog {
		for name, component := range byName {
			if component.Fields != nil {
				stripFieldDocs(component.Fields)
			}

			byName[name] = component
		}
	}
}

func stripFieldDocs(field *v1.ConfigField) {
	field.Doc = ""

	for key, child := range field.Children {
		stripFieldDocs(&child)
		field.Children[key] = child
	}
}
