// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/minuk-dev/opampcommander/pkg/apiserver/domain/agent"
	"github.com/minuk-dev/opampcommander/pkg/apiserver/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentUsecase creates a new instance of MockAgentUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentUsecase {
	mock := &MockAgentUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAgentUsecase is an autogenerated mock type for the AgentUsecase type
type MockAgentUsecase struct {
	mock.Mock
}

type MockAgentUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentUsecase) EXPECT() *MockAgentUsecase_Expecter {
	return &MockAgentUsecase_Expecter{mock: &_m.Mock}
}

// DeleteAgent provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) DeleteAgent(ctx context.Context, instanceUID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentUsecase_DeleteAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAgent'
type MockAgentUsecase_DeleteAgent_Call struct {
	*mock.Call
}

// DeleteAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockAgentUsecase_Expecter) DeleteAgent(ctx interface{}, instanceUID interface{}) *MockAgentUsecase_DeleteAgent_Call {
	return &MockAgentUsecase_DeleteAgent_Call{Call: _e.mock.On("DeleteAgent", ctx, instanceUID)}
}

func (_c *MockAgentUsecase_DeleteAgent_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockAgentUsecase_DeleteAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_DeleteAgent_Call) Return(err error) *MockAgentUsecase_DeleteAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentUsecase_DeleteAgent_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) error) *MockAgentUsecase_DeleteAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ForgetAgentLiveness provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) ForgetAgentLiveness(ctx context.Context, instanceUID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for ForgetAgentLiveness")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentUsecase_ForgetAgentLiveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgetAgentLiveness'
type MockAgentUsecase_ForgetAgentLiveness_Call struct {
	*mock.Call
}

// ForgetAgentLiveness is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockAgentUsecase_Expecter) ForgetAgentLiveness(ctx interface{}, instanceUID interface{}) *MockAgentUsecase_ForgetAgentLiveness_Call {
	return &MockAgentUsecase_ForgetAgentLiveness_Call{Call: _e.mock.On("ForgetAgentLiveness", ctx, instanceUID)}
}

func (_c *MockAgentUsecase_ForgetAgentLiveness_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockAgentUsecase_ForgetAgentLiveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_ForgetAgentLiveness_Call) Return(err error) *MockAgentUsecase_ForgetAgentLiveness_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentUsecase_ForgetAgentLiveness_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) error) *MockAgentUsecase_ForgetAgentLiveness_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgent provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) GetAgent(ctx context.Context, instanceUID uuid.UUID) (*agentmodel.Agent, error) {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 *agentmodel.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agentmodel.Agent, error)); ok {
		return returnFunc(ctx, instanceUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agentmodel.Agent); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentmodel.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, instanceUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockAgentUsecase_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockAgentUsecase_Expecter) GetAgent(ctx interface{}, instanceUID interface{}) *MockAgentUsecase_GetAgent_Call {
	return &MockAgentUsecase_GetAgent_Call{Call: _e.mock.On("GetAgent", ctx, instanceUID)}
}

func (_c *MockAgentUsecase_GetAgent_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockAgentUsecase_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_GetAgent_Call) Return(agent *agentmodel.Agent, err error) *MockAgentUsecase_GetAgent_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockAgentUsecase_GetAgent_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) (*agentmodel.Agent, error)) *MockAgentUsecase_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateAgent provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) GetOrCreateAgent(ctx context.Context, instanceUID uuid.UUID) (*agentmodel.Agent, error) {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateAgent")
	}

	var r0 *agentmodel.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agentmodel.Agent, error)); ok {
		return returnFunc(ctx, instanceUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agentmodel.Agent); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agentmodel.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, instanceUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_GetOrCreateAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateAgent'
type MockAgentUsecase_GetOrCreateAgent_Call struct {
	*mock.Call
}

// GetOrCreateAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockAgentUsecase_Expecter) GetOrCreateAgent(ctx interface{}, instanceUID interface{}) *MockAgentUsecase_GetOrCreateAgent_Call {
	return &MockAgentUsecase_GetOrCreateAgent_Call{Call: _e.mock.On("GetOrCreateAgent", ctx, instanceUID)}
}

func (_c *MockAgentUsecase_GetOrCreateAgent_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockAgentUsecase_GetOrCreateAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_GetOrCreateAgent_Call) Return(agent *agentmodel.Agent, err error) *MockAgentUsecase_GetOrCreateAgent_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockAgentUsecase_GetOrCreateAgent_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) (*agentmodel.Agent, error)) *MockAgentUsecase_GetOrCreateAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) ListAgents(ctx context.Context, namespace string, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error) {
	ret := _mock.Called(ctx, namespace, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 *model.ListResponse[*agentmodel.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)); ok {
		return returnFunc(ctx, namespace, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) *model.ListResponse[*agentmodel.Agent]); ok {
		r0 = returnFunc(ctx, namespace, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListResponse[*agentmodel.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, namespace, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockAgentUsecase_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - options *model.ListOptions
func (_e *MockAgentUsecase_Expecter) ListAgents(ctx interface{}, namespace interface{}, options interface{}) *MockAgentUsecase_ListAgents_Call {
	return &MockAgentUsecase_ListAgents_Call{Call: _e.mock.On("ListAgents", ctx, namespace, options)}
}

func (_c *MockAgentUsecase_ListAgents_Call) Run(run func(ctx context.Context, namespace string, options *model.ListOptions)) *MockAgentUsecase_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_ListAgents_Call) Return(listResponse *model.ListResponse[*agentmodel.Agent], err error) *MockAgentUsecase_ListAgents_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockAgentUsecase_ListAgents_Call) RunAndReturn(run func(ctx context.Context, namespace string, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)) *MockAgentUsecase_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentsBySelector provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) ListAgentsBySelector(ctx context.Context, selector agentmodel.AgentSelector, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error) {
	ret := _mock.Called(ctx, selector, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentsBySelector")
	}

	var r0 *model.ListResponse[*agentmodel.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, agentmodel.AgentSelector, *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)); ok {
		return returnFunc(ctx, selector, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, agentmodel.AgentSelector, *model.ListOptions) *model.ListResponse[*agentmodel.Agent]); ok {
		r0 = returnFunc(ctx, selector, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListResponse[*agentmodel.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, agentmodel.AgentSelector, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, selector, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_ListAgentsBySelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentsBySelector'
type MockAgentUsecase_ListAgentsBySelector_Call struct {
	*mock.Call
}

// ListAgentsBySelector is a helper method to define mock.On call
//   - ctx context.Context
//   - selector agentmodel.AgentSelector
//   - options *model.ListOptions
func (_e *MockAgentUsecase_Expecter) ListAgentsBySelector(ctx interface{}, selector interface{}, options interface{}) *MockAgentUsecase_ListAgentsBySelector_Call {
	return &MockAgentUsecase_ListAgentsBySelector_Call{Call: _e.mock.On("ListAgentsBySelector", ctx, selector, options)}
}

func (_c *MockAgentUsecase_ListAgentsBySelector_Call) Run(run func(ctx context.Context, selector agentmodel.AgentSelector, options *model.ListOptions)) *MockAgentUsecase_ListAgentsBySelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 agentmodel.AgentSelector
		if args[1] != nil {
			arg1 = args[1].(agentmodel.AgentSelector)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_ListAgentsBySelector_Call) Return(listResponse *model.ListResponse[*agentmodel.Agent], err error) *MockAgentUsecase_ListAgentsBySelector_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockAgentUsecase_ListAgentsBySelector_Call) RunAndReturn(run func(ctx context.Context, selector agentmodel.AgentSelector, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)) *MockAgentUsecase_ListAgentsBySelector_Call {
	_c.Call.Return(run)
	return _c
}

// PersistAgentLiveness provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) PersistAgentLiveness(ctx context.Context, liveness *agentmodel.AgentLiveness) error {
	ret := _mock.Called(ctx, liveness)

	if len(ret) == 0 {
		panic("no return value specified for PersistAgentLiveness")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agentmodel.AgentLiveness) error); ok {
		r0 = returnFunc(ctx, liveness)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentUsecase_PersistAgentLiveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistAgentLiveness'
type MockAgentUsecase_PersistAgentLiveness_Call struct {
	*mock.Call
}

// PersistAgentLiveness is a helper method to define mock.On call
//   - ctx context.Context
//   - liveness *agentmodel.AgentLiveness
func (_e *MockAgentUsecase_Expecter) PersistAgentLiveness(ctx interface{}, liveness interface{}) *MockAgentUsecase_PersistAgentLiveness_Call {
	return &MockAgentUsecase_PersistAgentLiveness_Call{Call: _e.mock.On("PersistAgentLiveness", ctx, liveness)}
}

func (_c *MockAgentUsecase_PersistAgentLiveness_Call) Run(run func(ctx context.Context, liveness *agentmodel.AgentLiveness)) *MockAgentUsecase_PersistAgentLiveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agentmodel.AgentLiveness
		if args[1] != nil {
			arg1 = args[1].(*agentmodel.AgentLiveness)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_PersistAgentLiveness_Call) Return(err error) *MockAgentUsecase_PersistAgentLiveness_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentUsecase_PersistAgentLiveness_Call) RunAndReturn(run func(ctx context.Context, liveness *agentmodel.AgentLiveness) error) *MockAgentUsecase_PersistAgentLiveness_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAgent provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) SaveAgent(ctx context.Context, agent *agentmodel.Agent) error {
	ret := _mock.Called(ctx, agent)

	if len(ret) == 0 {
		panic("no return value specified for SaveAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agentmodel.Agent) error); ok {
		r0 = returnFunc(ctx, agent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentUsecase_SaveAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAgent'
type MockAgentUsecase_SaveAgent_Call struct {
	*mock.Call
}

// SaveAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - agent *agentmodel.Agent
func (_e *MockAgentUsecase_Expecter) SaveAgent(ctx interface{}, agent interface{}) *MockAgentUsecase_SaveAgent_Call {
	return &MockAgentUsecase_SaveAgent_Call{Call: _e.mock.On("SaveAgent", ctx, agent)}
}

func (_c *MockAgentUsecase_SaveAgent_Call) Run(run func(ctx context.Context, agent *agentmodel.Agent)) *MockAgentUsecase_SaveAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agentmodel.Agent
		if args[1] != nil {
			arg1 = args[1].(*agentmodel.Agent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_SaveAgent_Call) Return(err error) *MockAgentUsecase_SaveAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentUsecase_SaveAgent_Call) RunAndReturn(run func(ctx context.Context, agent *agentmodel.Agent) error) *MockAgentUsecase_SaveAgent_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAgents provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) SearchAgents(ctx context.Context, namespace string, query string, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error) {
	ret := _mock.Called(ctx, namespace, query, options)

	if len(ret) == 0 {
		panic("no return value specified for SearchAgents")
	}

	var r0 *model.ListResponse[*agentmodel.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)); ok {
		return returnFunc(ctx, namespace, query, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.ListOptions) *model.ListResponse[*agentmodel.Agent]); ok {
		r0 = returnFunc(ctx, namespace, query, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListResponse[*agentmodel.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, namespace, query, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentUsecase_SearchAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAgents'
type MockAgentUsecase_SearchAgents_Call struct {
	*mock.Call
}

// SearchAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - query string
//   - options *model.ListOptions
func (_e *MockAgentUsecase_Expecter) SearchAgents(ctx interface{}, namespace interface{}, query interface{}, options interface{}) *MockAgentUsecase_SearchAgents_Call {
	return &MockAgentUsecase_SearchAgents_Call{Call: _e.mock.On("SearchAgents", ctx, namespace, query, options)}
}

func (_c *MockAgentUsecase_SearchAgents_Call) Run(run func(ctx context.Context, namespace string, query string, options *model.ListOptions)) *MockAgentUsecase_SearchAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *model.ListOptions
		if args[3] != nil {
			arg3 = args[3].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_SearchAgents_Call) Return(listResponse *model.ListResponse[*agentmodel.Agent], err error) *MockAgentUsecase_SearchAgents_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockAgentUsecase_SearchAgents_Call) RunAndReturn(run func(ctx context.Context, namespace string, query string, options *model.ListOptions) (*model.ListResponse[*agentmodel.Agent], error)) *MockAgentUsecase_SearchAgents_Call {
	_c.Call.Return(run)
	return _c
}

// TouchAgentLiveness provides a mock function for the type MockAgentUsecase
func (_mock *MockAgentUsecase) TouchAgentLiveness(ctx context.Context, agent *agentmodel.Agent, observedAt time.Time) bool {
	ret := _mock.Called(ctx, agent, observedAt)

	if len(ret) == 0 {
		panic("no return value specified for TouchAgentLiveness")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agentmodel.Agent, time.Time) bool); ok {
		r0 = returnFunc(ctx, agent, observedAt)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgentUsecase_TouchAgentLiveness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchAgentLiveness'
type MockAgentUsecase_TouchAgentLiveness_Call struct {
	*mock.Call
}

// TouchAgentLiveness is a helper method to define mock.On call
//   - ctx context.Context
//   - agent *agentmodel.Agent
//   - observedAt time.Time
func (_e *MockAgentUsecase_Expecter) TouchAgentLiveness(ctx interface{}, agent interface{}, observedAt interface{}) *MockAgentUsecase_TouchAgentLiveness_Call {
	return &MockAgentUsecase_TouchAgentLiveness_Call{Call: _e.mock.On("TouchAgentLiveness", ctx, agent, observedAt)}
}

func (_c *MockAgentUsecase_TouchAgentLiveness_Call) Run(run func(ctx context.Context, agent *agentmodel.Agent, observedAt time.Time)) *MockAgentUsecase_TouchAgentLiveness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agentmodel.Agent
		if args[1] != nil {
			arg1 = args[1].(*agentmodel.Agent)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentUsecase_TouchAgentLiveness_Call) Return(b bool) *MockAgentUsecase_TouchAgentLiveness_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgentUsecase_TouchAgentLiveness_Call) RunAndReturn(run func(ctx context.Context, agent *agentmodel.Agent, observedAt time.Time) bool) *MockAgentUsecase_TouchAgentLiveness_Call {
	_c.Call.Return(run)
	return _c
}
