{{- if and .Values.web.enabled .Values.web.ingress.enabled }}
{{- $fullname := include "opampcommander.web.fullname" . }}
{{- $port := .Values.web.service.port }}
{{- $ingress := .Values.web.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opampcommander.web.labels" . | nindent 4 }}
  {{- with (merge (dict) $ingress.annotations (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ $port }}
          {{- end }}
    {{- end }}
{{- end }}
