{{- if and .Values.web.enabled .Values.web.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opampcommander.web.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opampcommander.web.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.web.serviceAccount.annotations (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.web.serviceAccount.automountServiceAccountToken }}
{{- end }}
