#!/usr/bin/env bash
#
# gen-remoteconfigschema.sh — regenerate the pre-built RemoteConfigSchema library.
#
# The library mirrors the schema registry at
# https://github.com/minuk-dev/otelcol-config-schemas, whose files are generated by
# tools/schemagen in https://github.com/minuk-dev/otelcol-config-lint from each
# release's upstream metadata.yaml, its components' Config structs, and the
# config.schema.yaml the collector publishes from v0.150.0 on. Every release the
# registry indexes is rendered here as a RemoteConfigSchema manifest, without the field
# documentation — the server validates configs, it does not document them.
#
# Usage:
#   hack/gen-remoteconfigschema.sh                    # every release the registry has
#   DISTS="contrib" hack/gen-remoteconfigschema.sh    # one distribution
#   VERSIONS="v0.157.0" hack/gen-remoteconfigschema.sh
#   SCHEMA_LOCATION=../otelcol-config-schemas hack/gen-remoteconfigschema.sh
#   FORCE=1 hack/gen-remoteconfigschema.sh            # re-render existing files
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${OUT_DIR:-$REPO_ROOT/configs/apiserver/initial/remoteconfigschema}"
SCHEMA_LOCATION="${SCHEMA_LOCATION:-https://raw.githubusercontent.com/minuk-dev/otelcol-config-schemas/main}"
OPAMPCTL="${OPAMPCTL:-$REPO_ROOT/.bin/opampctl}"
NAMESPACE="${NAMESPACE:-default}"

log() { printf '%s\n' "$*" >&2; }

# read_index prints the registry's index.json, from a URL or a local checkout.
read_index() {
  case "$SCHEMA_LOCATION" in
  http://* | https://*) curl -fsSL "${SCHEMA_LOCATION%/}/index.json" ;;
  *) cat "$SCHEMA_LOCATION/index.json" ;;
  esac
}

# binary_for <distribution> prints the binary name the distribution builds.
binary_for() {
  case "$1" in
  core) printf 'otelcol' ;;
  *) printf 'otelcol-%s' "$1" ;;
  esac
}

if [[ ! -x "$OPAMPCTL" ]]; then
  log "building opampctl -> $OPAMPCTL"
  mkdir -p "$(dirname "$OPAMPCTL")"
  (cd "$REPO_ROOT" && go build -o "$OPAMPCTL" ./cmd/opampctl)
fi

mkdir -p "$OUT_DIR"

index="$(read_index)"
dists="${DISTS:-$(printf '%s' "$index" | jq -r '.distributions | keys[]')}"

for dist in $dists; do
  versions="${VERSIONS:-$(printf '%s' "$index" | jq -r --arg d "$dist" '.distributions[$d][]')}"
  binary="$(binary_for "$dist")"

  for version in $versions; do
    out="$OUT_DIR/${binary}-${version#v}.yaml"

    if [[ -f "$out" && "${FORCE:-0}" != "1" ]]; then
      log "skip $(basename "$out") (exists)"
      continue
    fi

    log "rendering $(basename "$out")"
    "$OPAMPCTL" generate remoteconfigschema \
      --distribution "$dist" \
      --version "$version" \
      --schema-location "$SCHEMA_LOCATION" \
      --namespace "$NAMESPACE" \
      --strip-docs \
      --output yaml >"$out"
  done
done

log "wrote $(find "$OUT_DIR" -name '*.yaml' | wc -l | tr -d ' ') schemas to $OUT_DIR"
