{{- if and .Values.apiserver.enabled .Values.apiserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opampcommander.apiserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opampcommander.apiserver.labels" . | nindent 4 }}
  {{- with (merge (dict) .Values.apiserver.serviceAccount.annotations (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.apiserver.serviceAccount.automountServiceAccountToken }}
{{- end }}
