{{- if and .Values.apiserver.enabled .Values.apiserver.serviceMonitor.enabled }}
{{- $serviceMonitor := .Values.apiserver.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opampcommander.apiserver.fullname" . }}
  namespace: {{ $serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "opampcommander.apiserver.labels" . | nindent 4 }}
    {{- with $serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with (include "opampcommander.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "opampcommander.apiserver.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: management
      path: {{ include "opampcommander.apiserver.metricsPath" . }}
      interval: {{ $serviceMonitor.interval }}
      {{- with $serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
