// Code generated by mockery; DO NOT EDIT.
// Hand-crafted — run 'make prebuilt-mock' after adding to .mockery.yml to replace with auto-generated mocks.

package usecasemock

import (
	"context"

	"github.com/google/uuid"
	v1 "github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ---- MockUsecase (UserManageUsecase) ----

// NewMockUsecase creates a new instance of MockUsecase.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	m := &MockUsecase{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockUsecase is a mock type for the Usecase (UserManageUsecase) interface.
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

func (_m *MockUsecase) GetUser(ctx context.Context, uid uuid.UUID) (*v1.User, error) {
	ret := _m.Called(ctx, uid)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.User); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) GetUserByEmail(ctx context.Context, email string) (*v1.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) ListUsers(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.User], error) {
	ret := _m.Called(ctx, options)

	var r0 *v1.ListResponse[v1.User]
	if rf, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.User]); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.User])
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) CreateUser(ctx context.Context, user *v1.User) (*v1.User, error) {
	ret := _m.Called(ctx, user)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, *v1.User) *v1.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	ret := _m.Called(ctx, uid)

	return ret.Error(0)
}

func (_m *MockUsecase) GetMyProfile(ctx context.Context, email string) (*v1.UserProfileResponse, error) {
	ret := _m.Called(ctx, email)

	var r0 *v1.UserProfileResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.UserProfileResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserProfileResponse)
		}
	}

	return r0, ret.Error(1)
}
