// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/google/uuid"
	"github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUsecase
func (_mock *MockUsecase) CreateUser(ctx context.Context, user *v1.User) (*v1.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *v1.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.User) (*v1.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.User) *v1.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUsecase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *v1.User
func (_e *MockUsecase_Expecter) CreateUser(ctx interface{}, user interface{}) *MockUsecase_CreateUser_Call {
	return &MockUsecase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockUsecase_CreateUser_Call) Run(run func(ctx context.Context, user *v1.User)) *MockUsecase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.User
		if args[1] != nil {
			arg1 = args[1].(*v1.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_CreateUser_Call) Return(user1 *v1.User, err error) *MockUsecase_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUsecase_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *v1.User) (*v1.User, error)) *MockUsecase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type MockUsecase
func (_mock *MockUsecase) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUsecase_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
func (_e *MockUsecase_Expecter) DeleteUser(ctx interface{}, uid interface{}) *MockUsecase_DeleteUser_Call {
	return &MockUsecase_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, uid)}
}

func (_c *MockUsecase_DeleteUser_Call) Run(run func(ctx context.Context, uid uuid.UUID)) *MockUsecase_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_DeleteUser_Call) Return(err error) *MockUsecase_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID) error) *MockUsecase_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyProfile provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetMyProfile(ctx context.Context, email string) (*v1.UserProfileResponse, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetMyProfile")
	}

	var r0 *v1.UserProfileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.UserProfileResponse, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.UserProfileResponse); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserProfileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetMyProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyProfile'
type MockUsecase_GetMyProfile_Call struct {
	*mock.Call
}

// GetMyProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsecase_Expecter) GetMyProfile(ctx interface{}, email interface{}) *MockUsecase_GetMyProfile_Call {
	return &MockUsecase_GetMyProfile_Call{Call: _e.mock.On("GetMyProfile", ctx, email)}
}

func (_c *MockUsecase_GetMyProfile_Call) Run(run func(ctx context.Context, email string)) *MockUsecase_GetMyProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetMyProfile_Call) Return(userProfileResponse *v1.UserProfileResponse, err error) *MockUsecase_GetMyProfile_Call {
	_c.Call.Return(userProfileResponse, err)
	return _c
}

func (_c *MockUsecase_GetMyProfile_Call) RunAndReturn(run func(ctx context.Context, email string) (*v1.UserProfileResponse, error)) *MockUsecase_GetMyProfile_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetUser(ctx context.Context, uid uuid.UUID, options *model.GetOptions) (*v1.User, error) {
	ret := _mock.Called(ctx, uid, options)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *v1.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.GetOptions) (*v1.User, error)); ok {
		return returnFunc(ctx, uid, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *model.GetOptions) *v1.User); ok {
		r0 = returnFunc(ctx, uid, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *model.GetOptions) error); ok {
		r1 = returnFunc(ctx, uid, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUsecase_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uuid.UUID
//   - options *model.GetOptions
func (_e *MockUsecase_Expecter) GetUser(ctx interface{}, uid interface{}, options interface{}) *MockUsecase_GetUser_Call {
	return &MockUsecase_GetUser_Call{Call: _e.mock.On("GetUser", ctx, uid, options)}
}

func (_c *MockUsecase_GetUser_Call) Run(run func(ctx context.Context, uid uuid.UUID, options *model.GetOptions)) *MockUsecase_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *model.GetOptions
		if args[2] != nil {
			arg2 = args[2].(*model.GetOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_GetUser_Call) Return(user *v1.User, err error) *MockUsecase_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsecase_GetUser_Call) RunAndReturn(run func(ctx context.Context, uid uuid.UUID, options *model.GetOptions) (*v1.User, error)) *MockUsecase_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetUserByEmail(ctx context.Context, email string) (*v1.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *v1.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUsecase_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUsecase_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUsecase_GetUserByEmail_Call {
	return &MockUsecase_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUsecase_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUsecase_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetUserByEmail_Call) Return(user *v1.User, err error) *MockUsecase_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUsecase_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*v1.User, error)) *MockUsecase_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUsecase
func (_mock *MockUsecase) ListUsers(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.User], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *v1.ListResponse[v1.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*v1.ListResponse[v1.User], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.User]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.User])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUsecase_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockUsecase_Expecter) ListUsers(ctx interface{}, options interface{}) *MockUsecase_ListUsers_Call {
	return &MockUsecase_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, options)}
}

func (_c *MockUsecase_ListUsers_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockUsecase_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_ListUsers_Call) Return(listResponse *v1.ListResponse[v1.User], err error) *MockUsecase_ListUsers_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockUsecase_ListUsers_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.User], error)) *MockUsecase_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}
