// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/google/uuid"
	v1 "github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// ---- MockUsecase (UserManageUsecase) ----

// NewMockUsecase creates a new instance of MockUsecase.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	m := &MockUsecase{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockUsecase is a mock type for the Usecase (UserManageUsecase) interface.
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

func (_m *MockUsecase) GetUser(ctx context.Context, uid uuid.UUID) (*v1.User, error) {
	ret := _m.Called(ctx, uid)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.User); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) GetUserByEmail(ctx context.Context, email string) (*v1.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) ListUsers(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.User], error) {
	ret := _m.Called(ctx, options)

	var r0 *v1.ListResponse[v1.User]
	if rf, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.User]); ok {
		r0 = rf(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.User])
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) CreateUser(ctx context.Context, user *v1.User) (*v1.User, error) {
	ret := _m.Called(ctx, user)

	var r0 *v1.User
	if rf, ok := ret.Get(0).(func(context.Context, *v1.User) *v1.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.User)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockUsecase) DeleteUser(ctx context.Context, uid uuid.UUID) error {
	ret := _m.Called(ctx, uid)

	return ret.Error(0)
}

func (_m *MockUsecase) GetUserProfile(ctx context.Context, email string) (*v1.UserProfileResponse, error) {
	ret := _m.Called(ctx, email)

	var r0 *v1.UserProfileResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1.UserProfileResponse); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.UserProfileResponse)
		}
	}

	return r0, ret.Error(1)
}

// ---- MockRBACUsecase (RBACManageUsecase) ----

// NewMockRBACUsecase creates a new instance of MockRBACUsecase.
func NewMockRBACUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRBACUsecase {
	m := &MockRBACUsecase{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })

	return m
}

// MockRBACUsecase is a mock type for the RBACUsecase (RBACManageUsecase) interface.
type MockRBACUsecase struct {
	mock.Mock
}

type MockRBACUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRBACUsecase) EXPECT() *MockRBACUsecase_Expecter {
	return &MockRBACUsecase_Expecter{mock: &_m.Mock}
}

func (_m *MockRBACUsecase) CheckPermission(ctx context.Context, req *v1.CheckPermissionRequest) (*v1.CheckPermissionResponse, error) {
	ret := _m.Called(ctx, req)

	var r0 *v1.CheckPermissionResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.CheckPermissionRequest) *v1.CheckPermissionResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.CheckPermissionResponse)
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockRBACUsecase) GetUserRoles(ctx context.Context, userID uuid.UUID) (*v1.ListResponse[v1.Role], error) {
	ret := _m.Called(ctx, userID)

	var r0 *v1.ListResponse[v1.Role]
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.ListResponse[v1.Role]); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Role])
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockRBACUsecase) GetUserRoleBindings(ctx context.Context, userID uuid.UUID) (*v1.ListResponse[v1.RoleBinding], error) {
	ret := _m.Called(ctx, userID)

	var r0 *v1.ListResponse[v1.RoleBinding]
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.ListResponse[v1.RoleBinding]); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.RoleBinding])
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockRBACUsecase) GetUserPermissions(ctx context.Context, userID uuid.UUID) (*v1.ListResponse[v1.Permission], error) {
	ret := _m.Called(ctx, userID)

	var r0 *v1.ListResponse[v1.Permission]
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *v1.ListResponse[v1.Permission]); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Permission])
		}
	}

	return r0, ret.Error(1)
}

func (_m *MockRBACUsecase) SyncPolicies(ctx context.Context) error {
	ret := _m.Called(ctx)

	return ret.Error(0)
}
