// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/pkg/apiserver/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManageUsecase creates a new instance of MockManageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManageUsecase {
	mock := &MockManageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManageUsecase is an autogenerated mock type for the ManageUsecase type
type MockManageUsecase struct {
	mock.Mock
}

type MockManageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManageUsecase) EXPECT() *MockManageUsecase_Expecter {
	return &MockManageUsecase_Expecter{mock: &_m.Mock}
}

// GetContainer provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) GetContainer(ctx context.Context, id string) (*v1.Container, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetContainer")
	}

	var r0 *v1.Container
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.Container, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.Container); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Container)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_GetContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainer'
type MockManageUsecase_GetContainer_Call struct {
	*mock.Call
}

// GetContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockManageUsecase_Expecter) GetContainer(ctx interface{}, id interface{}) *MockManageUsecase_GetContainer_Call {
	return &MockManageUsecase_GetContainer_Call{Call: _e.mock.On("GetContainer", ctx, id)}
}

func (_c *MockManageUsecase_GetContainer_Call) Run(run func(ctx context.Context, id string)) *MockManageUsecase_GetContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_GetContainer_Call) Return(container *v1.Container, err error) *MockManageUsecase_GetContainer_Call {
	_c.Call.Return(container, err)
	return _c
}

func (_c *MockManageUsecase_GetContainer_Call) RunAndReturn(run func(ctx context.Context, id string) (*v1.Container, error)) *MockManageUsecase_GetContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentsByContainer provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListAgentsByContainer(ctx context.Context, id string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error) {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentsByContainer")
	}

	var r0 *v1.ListResponse[v1.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) (*v1.ListResponse[v1.Agent], error)); ok {
		return returnFunc(ctx, id, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) *v1.ListResponse[v1.Agent]); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, id, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListAgentsByContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentsByContainer'
type MockManageUsecase_ListAgentsByContainer_Call struct {
	*mock.Call
}

// ListAgentsByContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListAgentsByContainer(ctx interface{}, id interface{}, options interface{}) *MockManageUsecase_ListAgentsByContainer_Call {
	return &MockManageUsecase_ListAgentsByContainer_Call{Call: _e.mock.On("ListAgentsByContainer", ctx, id, options)}
}

func (_c *MockManageUsecase_ListAgentsByContainer_Call) Run(run func(ctx context.Context, id string, options *model.ListOptions)) *MockManageUsecase_ListAgentsByContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListAgentsByContainer_Call) Return(listResponse *v1.ListResponse[v1.Agent], err error) *MockManageUsecase_ListAgentsByContainer_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListAgentsByContainer_Call) RunAndReturn(run func(ctx context.Context, id string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error)) *MockManageUsecase_ListAgentsByContainer_Call {
	_c.Call.Return(run)
	return _c
}

// ListContainers provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListContainers(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Container], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListContainers")
	}

	var r0 *v1.ListResponse[v1.Container]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*v1.ListResponse[v1.Container], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.Container]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Container])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockManageUsecase_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListContainers(ctx interface{}, options interface{}) *MockManageUsecase_ListContainers_Call {
	return &MockManageUsecase_ListContainers_Call{Call: _e.mock.On("ListContainers", ctx, options)}
}

func (_c *MockManageUsecase_ListContainers_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockManageUsecase_ListContainers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListContainers_Call) Return(listResponse *v1.ListResponse[v1.Container], err error) *MockManageUsecase_ListContainers_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListContainers_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Container], error)) *MockManageUsecase_ListContainers_Call {
	_c.Call.Return(run)
	return _c
}
