version: '3'

services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/go:1-1.24-bookworm"
    network_mode: service:db
    command: sleep infinity
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=opampcommander
volumes:
  mongodb-data:
