// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	v1 "github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// CreateAgentPackage provides a mock function for the type MockUsecase
func (_mock *MockUsecase) CreateAgentPackage(ctx context.Context, agentPackage *v1.AgentPackage) (*v1.AgentPackage, error) {
	ret := _mock.Called(ctx, agentPackage)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgentPackage")
	}

	var r0 *v1.AgentPackage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.AgentPackage) (*v1.AgentPackage, error)); ok {
		return returnFunc(ctx, agentPackage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.AgentPackage) *v1.AgentPackage); ok {
		r0 = returnFunc(ctx, agentPackage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AgentPackage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.AgentPackage) error); ok {
		r1 = returnFunc(ctx, agentPackage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_CreateAgentPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgentPackage'
type MockUsecase_CreateAgentPackage_Call struct {
	*mock.Call
}

// CreateAgentPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - agentPackage *v1.AgentPackage
func (_e *MockUsecase_Expecter) CreateAgentPackage(ctx interface{}, agentPackage interface{}) *MockUsecase_CreateAgentPackage_Call {
	return &MockUsecase_CreateAgentPackage_Call{Call: _e.mock.On("CreateAgentPackage", ctx, agentPackage)}
}

func (_c *MockUsecase_CreateAgentPackage_Call) Run(run func(ctx context.Context, agentPackage *v1.AgentPackage)) *MockUsecase_CreateAgentPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.AgentPackage
		if args[1] != nil {
			arg1 = args[1].(*v1.AgentPackage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_CreateAgentPackage_Call) Return(agentPackage *v1.AgentPackage, err error) *MockUsecase_CreateAgentPackage_Call {
	_c.Call.Return(agentPackage, err)
	return _c
}

func (_c *MockUsecase_CreateAgentPackage_Call) RunAndReturn(run func(ctx context.Context, agentPackage *v1.AgentPackage) (*v1.AgentPackage, error)) *MockUsecase_CreateAgentPackage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAgentPackage provides a mock function for the type MockUsecase
func (_mock *MockUsecase) DeleteAgentPackage(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAgentPackage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUsecase_DeleteAgentPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAgentPackage'
type MockUsecase_DeleteAgentPackage_Call struct {
	*mock.Call
}

// DeleteAgentPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUsecase_Expecter) DeleteAgentPackage(ctx interface{}, name interface{}) *MockUsecase_DeleteAgentPackage_Call {
	return &MockUsecase_DeleteAgentPackage_Call{Call: _e.mock.On("DeleteAgentPackage", ctx, name)}
}

func (_c *MockUsecase_DeleteAgentPackage_Call) Run(run func(ctx context.Context, name string)) *MockUsecase_DeleteAgentPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_DeleteAgentPackage_Call) Return(err error) *MockUsecase_DeleteAgentPackage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUsecase_DeleteAgentPackage_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockUsecase_DeleteAgentPackage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentPackage provides a mock function for the type MockUsecase
func (_mock *MockUsecase) GetAgentPackage(ctx context.Context, name string) (*v1.AgentPackage, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentPackage")
	}

	var r0 *v1.AgentPackage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.AgentPackage, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.AgentPackage); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AgentPackage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_GetAgentPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentPackage'
type MockUsecase_GetAgentPackage_Call struct {
	*mock.Call
}

// GetAgentPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockUsecase_Expecter) GetAgentPackage(ctx interface{}, name interface{}) *MockUsecase_GetAgentPackage_Call {
	return &MockUsecase_GetAgentPackage_Call{Call: _e.mock.On("GetAgentPackage", ctx, name)}
}

func (_c *MockUsecase_GetAgentPackage_Call) Run(run func(ctx context.Context, name string)) *MockUsecase_GetAgentPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_GetAgentPackage_Call) Return(agentPackage *v1.AgentPackage, err error) *MockUsecase_GetAgentPackage_Call {
	_c.Call.Return(agentPackage, err)
	return _c
}

func (_c *MockUsecase_GetAgentPackage_Call) RunAndReturn(run func(ctx context.Context, name string) (*v1.AgentPackage, error)) *MockUsecase_GetAgentPackage_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentPackages provides a mock function for the type MockUsecase
func (_mock *MockUsecase) ListAgentPackages(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.AgentPackage], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentPackages")
	}

	var r0 *v1.ListResponse[v1.AgentPackage]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*v1.ListResponse[v1.AgentPackage], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.AgentPackage]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.AgentPackage])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_ListAgentPackages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentPackages'
type MockUsecase_ListAgentPackages_Call struct {
	*mock.Call
}

// ListAgentPackages is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockUsecase_Expecter) ListAgentPackages(ctx interface{}, options interface{}) *MockUsecase_ListAgentPackages_Call {
	return &MockUsecase_ListAgentPackages_Call{Call: _e.mock.On("ListAgentPackages", ctx, options)}
}

func (_c *MockUsecase_ListAgentPackages_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockUsecase_ListAgentPackages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_ListAgentPackages_Call) Return(v *v1.ListResponse[v1.AgentPackage], err error) *MockUsecase_ListAgentPackages_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockUsecase_ListAgentPackages_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.AgentPackage], error)) *MockUsecase_ListAgentPackages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAgentPackage provides a mock function for the type MockUsecase
func (_mock *MockUsecase) UpdateAgentPackage(ctx context.Context, name string, agentPackage *v1.AgentPackage) (*v1.AgentPackage, error) {
	ret := _mock.Called(ctx, name, agentPackage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAgentPackage")
	}

	var r0 *v1.AgentPackage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.AgentPackage) (*v1.AgentPackage, error)); ok {
		return returnFunc(ctx, name, agentPackage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1.AgentPackage) *v1.AgentPackage); ok {
		r0 = returnFunc(ctx, name, agentPackage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.AgentPackage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v1.AgentPackage) error); ok {
		r1 = returnFunc(ctx, name, agentPackage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_UpdateAgentPackage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAgentPackage'
type MockUsecase_UpdateAgentPackage_Call struct {
	*mock.Call
}

// UpdateAgentPackage is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - agentPackage *v1.AgentPackage
func (_e *MockUsecase_Expecter) UpdateAgentPackage(ctx interface{}, name interface{}, agentPackage interface{}) *MockUsecase_UpdateAgentPackage_Call {
	return &MockUsecase_UpdateAgentPackage_Call{Call: _e.mock.On("UpdateAgentPackage", ctx, name, agentPackage)}
}

func (_c *MockUsecase_UpdateAgentPackage_Call) Run(run func(ctx context.Context, name string, agentPackage *v1.AgentPackage)) *MockUsecase_UpdateAgentPackage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1.AgentPackage
		if args[2] != nil {
			arg2 = args[2].(*v1.AgentPackage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUsecase_UpdateAgentPackage_Call) Return(agentPackage1 *v1.AgentPackage, err error) *MockUsecase_UpdateAgentPackage_Call {
	_c.Call.Return(agentPackage1, err)
	return _c
}

func (_c *MockUsecase_UpdateAgentPackage_Call) RunAndReturn(run func(ctx context.Context, name string, agentPackage *v1.AgentPackage) (*v1.AgentPackage, error)) *MockUsecase_UpdateAgentPackage_Call {
	_c.Call.Return(run)
	return _c
}
