// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/google/uuid"
	"github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManageUsecase creates a new instance of MockManageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManageUsecase {
	mock := &MockManageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManageUsecase is an autogenerated mock type for the ManageUsecase type
type MockManageUsecase struct {
	mock.Mock
}

type MockManageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManageUsecase) EXPECT() *MockManageUsecase_Expecter {
	return &MockManageUsecase_Expecter{mock: &_m.Mock}
}

// GetAgent provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) GetAgent(ctx context.Context, namespace string, instanceUID uuid.UUID) (*v1.Agent, error) {
	ret := _mock.Called(ctx, namespace, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 *v1.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) (*v1.Agent, error)); ok {
		return returnFunc(ctx, namespace, instanceUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) *v1.Agent); ok {
		r0 = returnFunc(ctx, namespace, instanceUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, namespace, instanceUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockManageUsecase_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - instanceUID uuid.UUID
func (_e *MockManageUsecase_Expecter) GetAgent(ctx interface{}, namespace interface{}, instanceUID interface{}) *MockManageUsecase_GetAgent_Call {
	return &MockManageUsecase_GetAgent_Call{Call: _e.mock.On("GetAgent", ctx, namespace, instanceUID)}
}

func (_c *MockManageUsecase_GetAgent_Call) Run(run func(ctx context.Context, namespace string, instanceUID uuid.UUID)) *MockManageUsecase_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_GetAgent_Call) Return(agent *v1.Agent, err error) *MockManageUsecase_GetAgent_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockManageUsecase_GetAgent_Call) RunAndReturn(run func(ctx context.Context, namespace string, instanceUID uuid.UUID) (*v1.Agent, error)) *MockManageUsecase_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListAgents(ctx context.Context, namespace string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error) {
	ret := _mock.Called(ctx, namespace, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 *v1.ListResponse[v1.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) (*v1.ListResponse[v1.Agent], error)); ok {
		return returnFunc(ctx, namespace, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) *v1.ListResponse[v1.Agent]); ok {
		r0 = returnFunc(ctx, namespace, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, namespace, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockManageUsecase_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListAgents(ctx interface{}, namespace interface{}, options interface{}) *MockManageUsecase_ListAgents_Call {
	return &MockManageUsecase_ListAgents_Call{Call: _e.mock.On("ListAgents", ctx, namespace, options)}
}

func (_c *MockManageUsecase_ListAgents_Call) Run(run func(ctx context.Context, namespace string, options *model.ListOptions)) *MockManageUsecase_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListAgents_Call) Return(listResponse *v1.ListResponse[v1.Agent], err error) *MockManageUsecase_ListAgents_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListAgents_Call) RunAndReturn(run func(ctx context.Context, namespace string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error)) *MockManageUsecase_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAgents provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) SearchAgents(ctx context.Context, namespace string, query string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error) {
	ret := _mock.Called(ctx, namespace, query, options)

	if len(ret) == 0 {
		panic("no return value specified for SearchAgents")
	}

	var r0 *v1.ListResponse[v1.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.ListOptions) (*v1.ListResponse[v1.Agent], error)); ok {
		return returnFunc(ctx, namespace, query, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *model.ListOptions) *v1.ListResponse[v1.Agent]); ok {
		r0 = returnFunc(ctx, namespace, query, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, namespace, query, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_SearchAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAgents'
type MockManageUsecase_SearchAgents_Call struct {
	*mock.Call
}

// SearchAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - query string
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) SearchAgents(ctx interface{}, namespace interface{}, query interface{}, options interface{}) *MockManageUsecase_SearchAgents_Call {
	return &MockManageUsecase_SearchAgents_Call{Call: _e.mock.On("SearchAgents", ctx, namespace, query, options)}
}

func (_c *MockManageUsecase_SearchAgents_Call) Run(run func(ctx context.Context, namespace string, query string, options *model.ListOptions)) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *model.ListOptions
		if args[3] != nil {
			arg3 = args[3].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManageUsecase_SearchAgents_Call) Return(listResponse *v1.ListResponse[v1.Agent], err error) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_SearchAgents_Call) RunAndReturn(run func(ctx context.Context, namespace string, query string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error)) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAgent provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) UpdateAgent(ctx context.Context, namespace string, instanceUID uuid.UUID, agent *v1.Agent) (*v1.Agent, error) {
	ret := _mock.Called(ctx, namespace, instanceUID, agent)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAgent")
	}

	var r0 *v1.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, *v1.Agent) (*v1.Agent, error)); ok {
		return returnFunc(ctx, namespace, instanceUID, agent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, *v1.Agent) *v1.Agent); ok {
		r0 = returnFunc(ctx, namespace, instanceUID, agent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, uuid.UUID, *v1.Agent) error); ok {
		r1 = returnFunc(ctx, namespace, instanceUID, agent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_UpdateAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAgent'
type MockManageUsecase_UpdateAgent_Call struct {
	*mock.Call
}

// UpdateAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - instanceUID uuid.UUID
//   - agent *v1.Agent
func (_e *MockManageUsecase_Expecter) UpdateAgent(ctx interface{}, namespace interface{}, instanceUID interface{}, agent interface{}) *MockManageUsecase_UpdateAgent_Call {
	return &MockManageUsecase_UpdateAgent_Call{Call: _e.mock.On("UpdateAgent", ctx, namespace, instanceUID, agent)}
}

func (_c *MockManageUsecase_UpdateAgent_Call) Run(run func(ctx context.Context, namespace string, instanceUID uuid.UUID, agent *v1.Agent)) *MockManageUsecase_UpdateAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *v1.Agent
		if args[3] != nil {
			arg3 = args[3].(*v1.Agent)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockManageUsecase_UpdateAgent_Call) Return(agent1 *v1.Agent, err error) *MockManageUsecase_UpdateAgent_Call {
	_c.Call.Return(agent1, err)
	return _c
}

func (_c *MockManageUsecase_UpdateAgent_Call) RunAndReturn(run func(ctx context.Context, namespace string, instanceUID uuid.UUID, agent *v1.Agent) (*v1.Agent, error)) *MockManageUsecase_UpdateAgent_Call {
	_c.Call.Return(run)
	return _c
}
