// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/google/uuid"
	"github.com/minuk-dev/opampcommander/api/v1/agent"
	"github.com/minuk-dev/opampcommander/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManageUsecase creates a new instance of MockManageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManageUsecase {
	mock := &MockManageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManageUsecase is an autogenerated mock type for the ManageUsecase type
type MockManageUsecase struct {
	mock.Mock
}

type MockManageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManageUsecase) EXPECT() *MockManageUsecase_Expecter {
	return &MockManageUsecase_Expecter{mock: &_m.Mock}
}

// GetAgent provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) GetAgent(ctx context.Context, instanceUID uuid.UUID) (*agent.Agent, error) {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for GetAgent")
	}

	var r0 *agent.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent.Agent, error)); ok {
		return returnFunc(ctx, instanceUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent.Agent); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, instanceUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_GetAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgent'
type MockManageUsecase_GetAgent_Call struct {
	*mock.Call
}

// GetAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockManageUsecase_Expecter) GetAgent(ctx interface{}, instanceUID interface{}) *MockManageUsecase_GetAgent_Call {
	return &MockManageUsecase_GetAgent_Call{Call: _e.mock.On("GetAgent", ctx, instanceUID)}
}

func (_c *MockManageUsecase_GetAgent_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockManageUsecase_GetAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_GetAgent_Call) Return(agent1 *agent.Agent, err error) *MockManageUsecase_GetAgent_Call {
	_c.Call.Return(agent1, err)
	return _c
}

func (_c *MockManageUsecase_GetAgent_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) (*agent.Agent, error)) *MockManageUsecase_GetAgent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgents provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListAgents(ctx context.Context, options *model.ListOptions) (*agent.ListResponse, error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgents")
	}

	var r0 *agent.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*agent.ListResponse, error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *agent.ListResponse); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.ListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgents'
type MockManageUsecase_ListAgents_Call struct {
	*mock.Call
}

// ListAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListAgents(ctx interface{}, options interface{}) *MockManageUsecase_ListAgents_Call {
	return &MockManageUsecase_ListAgents_Call{Call: _e.mock.On("ListAgents", ctx, options)}
}

func (_c *MockManageUsecase_ListAgents_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockManageUsecase_ListAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListAgents_Call) Return(v *agent.ListResponse, err error) *MockManageUsecase_ListAgents_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockManageUsecase_ListAgents_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*agent.ListResponse, error)) *MockManageUsecase_ListAgents_Call {
	_c.Call.Return(run)
	return _c
}

// RestartAgent provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) RestartAgent(ctx context.Context, instanceUID uuid.UUID) error {
	ret := _mock.Called(ctx, instanceUID)

	if len(ret) == 0 {
		panic("no return value specified for RestartAgent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, instanceUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockManageUsecase_RestartAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartAgent'
type MockManageUsecase_RestartAgent_Call struct {
	*mock.Call
}

// RestartAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
func (_e *MockManageUsecase_Expecter) RestartAgent(ctx interface{}, instanceUID interface{}) *MockManageUsecase_RestartAgent_Call {
	return &MockManageUsecase_RestartAgent_Call{Call: _e.mock.On("RestartAgent", ctx, instanceUID)}
}

func (_c *MockManageUsecase_RestartAgent_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID)) *MockManageUsecase_RestartAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_RestartAgent_Call) Return(err error) *MockManageUsecase_RestartAgent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockManageUsecase_RestartAgent_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID) error) *MockManageUsecase_RestartAgent_Call {
	_c.Call.Return(run)
	return _c
}

// SearchAgents provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) SearchAgents(ctx context.Context, query string, options *model.ListOptions) (*agent.ListResponse, error) {
	ret := _mock.Called(ctx, query, options)

	if len(ret) == 0 {
		panic("no return value specified for SearchAgents")
	}

	var r0 *agent.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) (*agent.ListResponse, error)); ok {
		return returnFunc(ctx, query, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) *agent.ListResponse); ok {
		r0 = returnFunc(ctx, query, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.ListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, query, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_SearchAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchAgents'
type MockManageUsecase_SearchAgents_Call struct {
	*mock.Call
}

// SearchAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) SearchAgents(ctx interface{}, query interface{}, options interface{}) *MockManageUsecase_SearchAgents_Call {
	return &MockManageUsecase_SearchAgents_Call{Call: _e.mock.On("SearchAgents", ctx, query, options)}
}

func (_c *MockManageUsecase_SearchAgents_Call) Run(run func(ctx context.Context, query string, options *model.ListOptions)) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_SearchAgents_Call) Return(v *agent.ListResponse, err error) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockManageUsecase_SearchAgents_Call) RunAndReturn(run func(ctx context.Context, query string, options *model.ListOptions) (*agent.ListResponse, error)) *MockManageUsecase_SearchAgents_Call {
	_c.Call.Return(run)
	return _c
}

// SetNewInstanceUID provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) SetNewInstanceUID(ctx context.Context, instanceUID uuid.UUID, newInstanceUID uuid.UUID) (*agent.Agent, error) {
	ret := _mock.Called(ctx, instanceUID, newInstanceUID)

	if len(ret) == 0 {
		panic("no return value specified for SetNewInstanceUID")
	}

	var r0 *agent.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*agent.Agent, error)); ok {
		return returnFunc(ctx, instanceUID, newInstanceUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *agent.Agent); ok {
		r0 = returnFunc(ctx, instanceUID, newInstanceUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, instanceUID, newInstanceUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_SetNewInstanceUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNewInstanceUID'
type MockManageUsecase_SetNewInstanceUID_Call struct {
	*mock.Call
}

// SetNewInstanceUID is a helper method to define mock.On call
//   - ctx context.Context
//   - instanceUID uuid.UUID
//   - newInstanceUID uuid.UUID
func (_e *MockManageUsecase_Expecter) SetNewInstanceUID(ctx interface{}, instanceUID interface{}, newInstanceUID interface{}) *MockManageUsecase_SetNewInstanceUID_Call {
	return &MockManageUsecase_SetNewInstanceUID_Call{Call: _e.mock.On("SetNewInstanceUID", ctx, instanceUID, newInstanceUID)}
}

func (_c *MockManageUsecase_SetNewInstanceUID_Call) Run(run func(ctx context.Context, instanceUID uuid.UUID, newInstanceUID uuid.UUID)) *MockManageUsecase_SetNewInstanceUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_SetNewInstanceUID_Call) Return(agent1 *agent.Agent, err error) *MockManageUsecase_SetNewInstanceUID_Call {
	_c.Call.Return(agent1, err)
	return _c
}

func (_c *MockManageUsecase_SetNewInstanceUID_Call) RunAndReturn(run func(ctx context.Context, instanceUID uuid.UUID, newInstanceUID uuid.UUID) (*agent.Agent, error)) *MockManageUsecase_SetNewInstanceUID_Call {
	_c.Call.Return(run)
	return _c
}
