// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agentgroups": {
            "get": {
                "description": "Retrieves a list of agent groups with pagination options.",
                "tags": [
                    "agentgroup"
                ],
                "summary": "List Agent Groups",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of agent groups to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token to continue listing agent groups",
                        "name": "continue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-AgentGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new agent group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentgroup"
                ],
                "summary": "Create Agent Group",
                "parameters": [
                    {
                        "description": "Agent Group to create",
                        "name": "agentGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentGroup"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/AgentGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            }
        },
        "/api/v1/agentgroups/{name}": {
            "get": {
                "description": "Retrieve an agent group by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentgroup"
                ],
                "summary": "Get Agent Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing agent group.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentgroup"
                ],
                "summary": "Update Agent Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent Group Name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Agent Group",
                        "name": "agentGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentGroup"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentGroup"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            },
            "delete": {
                "description": "Mark an agent group as deleted.",
                "tags": [
                    "agentgroup"
                ],
                "summary": "Delete Agent Group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent Group ID",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            }
        },
        "/api/v1/agentpackages": {
            "get": {
                "description": "Retrieve a list of agent packages.",
                "tags": [
                    "agentpackage"
                ],
                "summary": "List Agent Packages",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of agent packages to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token to continue listing agent packages",
                        "name": "continue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-AgentPackage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new agent package.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentpackage"
                ],
                "summary": "Create Agent Package",
                "parameters": [
                    {
                        "description": "Agent Package to create",
                        "name": "agentPackage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentPackage"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/AgentPackage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/agentpackages/{name}": {
            "get": {
                "description": "Retrieve an agent package by its name.",
                "tags": [
                    "agentpackage"
                ],
                "summary": "Get Agent Package",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the agent package",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentPackage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing agent package.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentpackage"
                ],
                "summary": "Update Agent Package",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the agent package",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated Agent Package",
                        "name": "agentPackage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/AgentPackage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AgentPackage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an agent package by its name.",
                "tags": [
                    "agentpackage"
                ],
                "summary": "Delete Agent Package",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the agent package",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/agents": {
            "get": {
                "description": "Retrieve a list of agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "List Agents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Maximum number of agents to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token to continue listing agents",
                        "name": "continue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/search": {
            "get": {
                "description": "Search agents by instance UID query.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Search Agents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query for instance UID",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of agents to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Token to continue listing agents",
                        "name": "continue",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{id}": {
            "get": {
                "description": "Retrieve an agent by its instance UID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Get Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance UID of the agent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an agent's metadata \u0026 spec.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agent"
                ],
                "summary": "Update Agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Instance UID of the agent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Agent update request",
                        "name": "agent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Agent"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/ErrorModel"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/basic": {
            "get": {
                "description": "Authenticate using basic auth credentials.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "basic"
                ],
                "summary": "Basic Authentication",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AuthnTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/github": {
            "get": {
                "description": "Returns the GitHub OAuth2 authentication URL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "github"
                ],
                "summary": "GitHub OAuth2 Authentication",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/OAuth2AuthCodeURLResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/github/device": {
            "get": {
                "description": "Initiates device authorization for GitHub OAuth2.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "github"
                ],
                "summary": "GitHub Device Authentication",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/DeviceAuthnTokenResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/github/device/exchange": {
            "get": {
                "description": "Exchanges a device code for an authentication token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "github"
                ],
                "summary": "GitHub Device Code Exchange",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device code to exchange",
                        "name": "device_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional expiry time in RFC3339 format",
                        "name": "expiry",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AuthnTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/info": {
            "get": {
                "description": "Get Authentication Info.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "basic"
                ],
                "summary": "Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/InfoResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/connections": {
            "get": {
                "description": "Retrieve a list of all connections.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connection"
                ],
                "summary": "List Connections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-Connection"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/ping": {
            "get": {
                "description": "Ping the server to check if it is alive.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ping"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/PingResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/servers": {
            "get": {
                "description": "Retrieve a list of all alive servers.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "server"
                ],
                "summary": "List Servers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ListResponse-Server"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/version": {
            "get": {
                "description": "Retrieve the server version information.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "version"
                ],
                "summary": "Get Server Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/VersionInfo"
                        }
                    }
                }
            }
        },
        "/auth/github": {
            "get": {
                "description": "Redirects to GitHub for OAuth2 authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "github"
                ],
                "summary": "GitHub OAuth2 Authentication",
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/github/callback": {
            "get": {
                "description": "Exchanges the code received from GitHub for an authentication token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth",
                    "github"
                ],
                "summary": "GitHub OAuth2 Callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "State parameter to prevent CSRF attacks",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Code received from GitHub after authentication",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/AuthnTokenResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Check if the service is healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Check if the service is ready",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Agent": {
            "type": "object",
            "properties": {
                "metadata": {
                    "description": "Metadata contains identifying information about the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentMetadata"
                        }
                    ]
                },
                "spec": {
                    "description": "Spec contains the desired configuration for the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentSpec"
                        }
                    ]
                },
                "status": {
                    "description": "Status contains the observed state of the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentStatus"
                        }
                    ]
                }
            }
        },
        "AgentAvailableComponents": {
            "type": "object",
            "properties": {
                "components": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/ComponentDetails"
                    }
                }
            }
        },
        "AgentComponentHealth": {
            "type": "object",
            "properties": {
                "componentsMap": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "healthy": {
                    "type": "boolean"
                },
                "lastError": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "statusTime": {
                    "type": "string"
                }
            }
        },
        "AgentConditionStatus": {
            "type": "string",
            "enum": [
                "True",
                "False",
                "Unknown"
            ],
            "x-enum-varnames": [
                "ConditionStatusTrue",
                "ConditionStatusFalse",
                "ConditionStatusUnknown"
            ]
        },
        "AgentConfigFile": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "contentType": {
                    "type": "string"
                }
            }
        },
        "AgentConfigMap": {
            "type": "object",
            "properties": {
                "configMap": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/AgentConfigFile"
                    }
                }
            }
        },
        "AgentCustomCapabilities": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "AgentDescription": {
            "type": "object",
            "properties": {
                "identifyingAttributes": {
                    "description": "IdentifyingAttributes are attributes that uniquely identify the agent.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "nonIdentifyingAttributes": {
                    "description": "NonIdentifyingAttributes are attributes that do not uniquely identify the agent.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "AgentEffectiveConfig": {
            "type": "object",
            "properties": {
                "configMap": {
                    "$ref": "#/definitions/AgentConfigMap"
                }
            }
        },
        "AgentGroup": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/AgentGroupMetadata"
                },
                "spec": {
                    "$ref": "#/definitions/AgentGroupSpec"
                },
                "status": {
                    "$ref": "#/definitions/AgentGroupStatus"
                }
            }
        },
        "AgentGroupMetadata": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/api_v1.Attributes"
                },
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "selector": {
                    "$ref": "#/definitions/api_v1.AgentSelector"
                }
            }
        },
        "AgentGroupSpec": {
            "type": "object",
            "properties": {
                "agentConfig": {
                    "$ref": "#/definitions/api_v1.AgentConfig"
                }
            }
        },
        "AgentGroupStatus": {
            "type": "object",
            "properties": {
                "conditions": {
                    "description": "Conditions is a list of conditions that apply to the agent group.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Condition"
                    }
                },
                "numAgents": {
                    "description": "NumAgents is the total number of agents in the agent group.",
                    "type": "integer"
                },
                "numConnectedAgents": {
                    "description": "NumConnectedAgents is the number of connected agents in the agent group.",
                    "type": "integer"
                },
                "numHealthyAgents": {
                    "description": "NumHealthyAgents is the number of healthy agents in the agent group.",
                    "type": "integer"
                },
                "numNotConnectedAgents": {
                    "description": "NumNotConnectedAgents is the number of not connected agents in the agent group.",
                    "type": "integer"
                },
                "numUnhealthyAgents": {
                    "description": "NumUnhealthyAgents is the number of unhealthy agents in the agent group.",
                    "type": "integer"
                }
            }
        },
        "AgentMetadata": {
            "type": "object",
            "properties": {
                "capabilities": {
                    "description": "Capabilities is a bitmask representing the capabilities of the agent.",
                    "type": "integer"
                },
                "customCapabilities": {
                    "description": "CustomCapabilities is a map of custom capabilities for the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentCustomCapabilities"
                        }
                    ]
                },
                "description": {
                    "description": "Description is a human-readable description of the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentDescription"
                        }
                    ]
                },
                "instanceUid": {
                    "description": "InstanceUID is a unique identifier for the agent instance.",
                    "type": "string"
                }
            }
        },
        "AgentPackage": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/AgentPackageMetadata"
                },
                "spec": {
                    "$ref": "#/definitions/AgentPackageSpec"
                },
                "status": {
                    "$ref": "#/definitions/AgentPackageStatus"
                }
            }
        },
        "AgentPackageMetadata": {
            "type": "object",
            "properties": {
                "attributes": {
                    "$ref": "#/definitions/github_com_minuk-dev_opampcommander_api_v1.Attributes"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "AgentPackageSpec": {
            "type": "object",
            "properties": {
                "contentHash": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "downloadUrl": {
                    "type": "string"
                },
                "hash": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "packageType": {
                    "type": "string"
                },
                "signature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "AgentPackageStatus": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Condition"
                    }
                }
            }
        },
        "AgentPackageStatusPackageEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name is the name of the package.",
                    "type": "string"
                }
            }
        },
        "AgentPackageStatuses": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "packages": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/AgentPackageStatusPackageEntry"
                    }
                },
                "serverProvidedAllPackagesHash": {
                    "type": "string"
                }
            }
        },
        "AgentSpec": {
            "type": "object",
            "properties": {
                "connectionSettings": {
                    "description": "ConnectionSettings contains connection settings for the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ConnectionSettings"
                        }
                    ]
                },
                "newInstanceUid": {
                    "description": "NewInstanceUID is a new instance UID to inform the agent of its new identity.",
                    "type": "string"
                },
                "packagesAvailable": {
                    "description": "PackagesAvailable is the packages available for the agent to download.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentSpecPackages"
                        }
                    ]
                },
                "remoteConfig": {
                    "description": "RemoteConfig is the remote configuration of the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentSpecRemoteConfig"
                        }
                    ]
                },
                "restartRequiredAt": {
                    "description": "RestartRequiredAt is the time when a restart was requested.\nIf this time is after the agent's start time, the agent should be restarted.",
                    "type": "string"
                }
            }
        },
        "AgentSpecPackages": {
            "type": "object",
            "properties": {
                "packages": {
                    "description": "Packages is a list of package names available for the agent.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "AgentSpecRemoteConfig": {
            "type": "object",
            "properties": {
                "remoteConfigNames": {
                    "description": "RemoteConfigNames is a list of remote config names applied to this agent.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "AgentStatus": {
            "type": "object",
            "properties": {
                "availableComponents": {
                    "description": "AvailableComponents lists components available on the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentAvailableComponents"
                        }
                    ]
                },
                "componentHealth": {
                    "description": "ComponentHealth is the health status of the agent's components.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentComponentHealth"
                        }
                    ]
                },
                "conditions": {
                    "description": "Conditions is a list of conditions that apply to the agent.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Condition"
                    }
                },
                "connected": {
                    "description": "Connected indicates if the agent is currently connected.",
                    "type": "boolean"
                },
                "connectionType": {
                    "description": "ConnectionType indicates the type of connection the agent is using.",
                    "type": "string"
                },
                "effectiveConfig": {
                    "description": "EffectiveConfig is the effective configuration of the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentEffectiveConfig"
                        }
                    ]
                },
                "lastReportedAt": {
                    "description": "LastReportedAt is the timestamp when the agent last reported its status.",
                    "type": "string"
                },
                "packageStatuses": {
                    "description": "PackageStatuses is a map of package statuses for the agent.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/AgentPackageStatuses"
                        }
                    ]
                },
                "sequenceNum": {
                    "description": "SequenceNum is the sequence number from the last AgentToServer message.",
                    "type": "integer"
                }
            }
        },
        "AuthnTokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token is the authentication token.",
                    "type": "string"
                }
            }
        },
        "ComponentDetails": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "Condition": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/AgentConditionStatus"
                },
                "type": {
                    "$ref": "#/definitions/ConditionType"
                }
            }
        },
        "ConditionType": {
            "type": "string",
            "enum": [
                "Created",
                "Updated",
                "Deleted",
                "Connected",
                "Healthy",
                "Configured",
                "Registered"
            ],
            "x-enum-varnames": [
                "ConditionTypeCreated",
                "ConditionTypeUpdated",
                "ConditionTypeDeleted",
                "ConditionTypeConnected",
                "ConditionTypeHealthy",
                "ConditionTypeConfigured",
                "ConditionTypeRegistered"
            ]
        },
        "Connection": {
            "type": "object",
            "properties": {
                "alive": {
                    "description": "Alive indicates whether the connection is currently alive.",
                    "type": "boolean"
                },
                "id": {
                    "description": "ID is the unique identifier of the connection.",
                    "type": "string"
                },
                "instanceUid": {
                    "description": "InstanceUID is the unique identifier of the agent instance.",
                    "type": "string"
                },
                "lastCommunicatedAt": {
                    "description": "LastCommunicatedAt is the timestamp of the last communication with the agent.",
                    "type": "string"
                },
                "type": {
                    "description": "Type is the type of connection (e.g., \"http\", \"websocket\").",
                    "type": "string"
                }
            }
        },
        "ConnectionSettings": {
            "type": "object",
            "properties": {
                "opamp": {
                    "description": "OpAMP contains OpAMP server connection settings.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/OpAMPConnectionSettings"
                        }
                    ]
                },
                "otherConnections": {
                    "description": "OtherConnections contains other connection settings mapped by name.",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/OtherConnectionSettings"
                    }
                },
                "ownLogs": {
                    "description": "OwnLogs contains own logs connection settings.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TelemetryConnectionSettings"
                        }
                    ]
                },
                "ownMetrics": {
                    "description": "OwnMetrics contains own metrics connection settings.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TelemetryConnectionSettings"
                        }
                    ]
                },
                "ownTraces": {
                    "description": "OwnTraces contains own traces connection settings.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TelemetryConnectionSettings"
                        }
                    ]
                }
            }
        },
        "DeviceAuthnTokenResponse": {
            "type": "object",
            "properties": {
                "deviceCode": {
                    "description": "DeviceCode",
                    "type": "string"
                },
                "expiry": {
                    "description": "Expiry is when the device code and user code expire",
                    "type": "string"
                },
                "interval": {
                    "description": "Interval is the duration in seconds that Poll should wait between requests",
                    "type": "integer"
                },
                "userCode": {
                    "description": "UserCode is the code the user should enter at the verification uri",
                    "type": "string"
                },
                "verificationUri": {
                    "description": "VerificationURI is where user should enter the user code",
                    "type": "string"
                },
                "verificationUriComplete": {
                    "description": "VerificationURIComplete (if populated) includes the user code in the verification URI.\nThis is typically shown to the user in non-textual form, such as a QR code.",
                    "type": "string"
                }
            }
        },
        "ErrorDetail": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "ErrorModel": {
            "type": "object",
            "properties": {
                "detail": {
                    "description": "Detail is a human-readable explanation specific to this occurrence of the problem.\nexample: \"Your request parameters didn't validate.\"",
                    "type": "string"
                },
                "errors": {
                    "description": "Errors provides additional error details.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ErrorDetail"
                    }
                },
                "instance": {
                    "description": "Instance is a URI reference that identifies the specific occurrence of the problem.",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the HTTP status code generated by the origin server for this occurrence of the problem.\nexample: 400",
                    "type": "integer"
                },
                "title": {
                    "description": "Title is a short, human-readable summary of the problem type.\nexample: \"Bad Request\"",
                    "type": "string"
                },
                "type": {
                    "description": "Type is a URI reference that identifies the problem type.\nexample: \"https://example.com/probs/out-of-credit\"",
                    "type": "string"
                }
            }
        },
        "InfoResponse": {
            "type": "object",
            "properties": {
                "authenticated": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "ListMeta": {
            "type": "object",
            "properties": {
                "continue": {
                    "type": "string"
                },
                "remainingItemCount": {
                    "type": "integer"
                }
            }
        },
        "ListResponse-Agent": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Agent"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/ListMeta"
                }
            }
        },
        "ListResponse-AgentGroup": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AgentGroup"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/ListMeta"
                }
            }
        },
        "ListResponse-AgentPackage": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/AgentPackage"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/ListMeta"
                }
            }
        },
        "ListResponse-Connection": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Connection"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/ListMeta"
                }
            }
        },
        "ListResponse-Server": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Server"
                    }
                },
                "kind": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/ListMeta"
                }
            }
        },
        "OAuth2AuthCodeURLResponse": {
            "type": "object",
            "properties": {
                "url": {
                    "description": "URL is the OAuth2 authorization URL.",
                    "type": "string"
                }
            }
        },
        "OpAMPConnectionSettings": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "Certificate contains TLS certificate information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TLSCertificate"
                        }
                    ]
                },
                "destinationEndpoint": {
                    "description": "DestinationEndpoint is the URL to connect to the OpAMP server.",
                    "type": "string"
                },
                "headers": {
                    "description": "Headers are HTTP headers to include in requests.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "OtherConnectionSettings": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "Certificate contains TLS certificate information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TLSCertificate"
                        }
                    ]
                },
                "destinationEndpoint": {
                    "description": "DestinationEndpoint is the URL to connect to.",
                    "type": "string"
                },
                "headers": {
                    "description": "Headers are HTTP headers to include in requests.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "PingResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message is the response message.",
                    "type": "string"
                }
            }
        },
        "Server": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ServerCondition"
                    }
                },
                "id": {
                    "type": "string"
                },
                "lastHeartbeatAt": {
                    "type": "string"
                }
            }
        },
        "ServerCondition": {
            "type": "object",
            "properties": {
                "lastTransitionTime": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/ServerConditionStatus"
                },
                "type": {
                    "$ref": "#/definitions/ServerConditionType"
                }
            }
        },
        "ServerConditionStatus": {
            "type": "string",
            "enum": [
                "True",
                "False",
                "Unknown"
            ],
            "x-enum-varnames": [
                "ServerConditionStatusTrue",
                "ServerConditionStatusFalse",
                "ServerConditionStatusUnknown"
            ]
        },
        "ServerConditionType": {
            "type": "string",
            "enum": [
                "Registered",
                "Alive"
            ],
            "x-enum-varnames": [
                "ServerConditionTypeRegistered",
                "ServerConditionTypeAlive"
            ]
        },
        "TLSCertificate": {
            "type": "object",
            "properties": {
                "caCert": {
                    "description": "CaCert is the PEM-encoded CA certificate.",
                    "type": "string"
                },
                "cert": {
                    "description": "Cert is the PEM-encoded certificate.",
                    "type": "string"
                },
                "privateKey": {
                    "description": "PrivateKey is the PEM-encoded private key.",
                    "type": "string"
                }
            }
        },
        "TelemetryConnectionSettings": {
            "type": "object",
            "properties": {
                "certificate": {
                    "description": "Certificate contains TLS certificate information.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/TLSCertificate"
                        }
                    ]
                },
                "destinationEndpoint": {
                    "description": "DestinationEndpoint is the URL to send telemetry data to.",
                    "type": "string"
                },
                "headers": {
                    "description": "Headers are HTTP headers to include in requests.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "VersionInfo": {
            "type": "object",
            "properties": {
                "buildDate": {
                    "type": "string"
                },
                "compiler": {
                    "type": "string"
                },
                "gitCommit": {
                    "type": "string"
                },
                "gitTreeState": {
                    "type": "string"
                },
                "gitVersion": {
                    "type": "string"
                },
                "goVersion": {
                    "type": "string"
                },
                "major": {
                    "type": "string"
                },
                "minor": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "api_v1.AgentConfig": {
            "type": "object",
            "properties": {
                "agentRemoteConfig": {
                    "$ref": "#/definitions/api_v1.AgentGroupRemoteConfig"
                },
                "connectionSettings": {
                    "$ref": "#/definitions/ConnectionSettings"
                }
            }
        },
        "api_v1.AgentGroupRemoteConfig": {
            "type": "object",
            "properties": {
                "agentRemoteConfigName": {
                    "description": "AgentRemoteConfigName is the name of a standalone remote configuration resource.",
                    "type": "string"
                },
                "agentRemoteConfigRef": {
                    "description": "AgentRemoteConfigRef is a reference to a standalone remote configuration resource.",
                    "type": "string"
                },
                "agentRemoteConfigSpec": {
                    "description": "AgentRemoteConfigSpec is the remote configuration to be applied to agents in this group.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api_v1.AgentRemoteConfigSpec"
                        }
                    ]
                }
            }
        },
        "api_v1.AgentRemoteConfigSpec": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api_v1.AgentSelector": {
            "type": "object",
            "properties": {
                "identifyingAttributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "nonIdentifyingAttributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "api_v1.Attributes": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "github_com_minuk-dev_opampcommander_api_v1.AgentConfig": {
            "type": "object",
            "properties": {
                "agentRemoteConfig": {
                    "$ref": "#/definitions/github_com_minuk-dev_opampcommander_api_v1.AgentGroupRemoteConfig"
                },
                "connectionSettings": {
                    "$ref": "#/definitions/ConnectionSettings"
                }
            }
        },
        "github_com_minuk-dev_opampcommander_api_v1.AgentGroupRemoteConfig": {
            "type": "object",
            "properties": {
                "agentRemoteConfigName": {
                    "description": "AgentRemoteConfigName is the name of a standalone remote configuration resource.",
                    "type": "string"
                },
                "agentRemoteConfigRef": {
                    "description": "AgentRemoteConfigRef is a reference to a standalone remote configuration resource.",
                    "type": "string"
                },
                "agentRemoteConfigSpec": {
                    "description": "AgentRemoteConfigSpec is the remote configuration to be applied to agents in this group.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_minuk-dev_opampcommander_api_v1.AgentRemoteConfigSpec"
                        }
                    ]
                }
            }
        },
        "github_com_minuk-dev_opampcommander_api_v1.AgentRemoteConfigSpec": {
            "type": "object",
            "properties": {
                "contentType": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "github_com_minuk-dev_opampcommander_api_v1.AgentSelector": {
            "type": "object",
            "properties": {
                "identifyingAttributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "nonIdentifyingAttributes": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_minuk-dev_opampcommander_api_v1.Attributes": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "OpAMP Commander API Server",
	Description:      "This is the API server for OpAMP Commander, providing endpoints for managing OpAMP agents.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
