apiVersion: v1
kind: RemoteConfigSchema
metadata:
    attributes: null
    createdAt: null
    name: otelcol-contrib-0.122.0
    namespace: default
spec:
    binary: otelcol-contrib
    components:
        connectors:
            - count
            - datadog
            - exceptions
            - failover
            - forward
            - grafanacloud
            - otlpjson
            - roundrobin
            - routing
            - servicegraph
            - signaltometrics
            - spanmetrics
            - sum
        exporters:
            - alibabacloud_logservice
            - awscloudwatchlogs
            - awsemf
            - awskinesis
            - awss3
            - awsxray
            - azuredataexplorer
            - azuremonitor
            - bmchelix
            - carbon
            - cassandra
            - clickhouse
            - coralogix
            - datadog
            - dataset
            - debug
            - doris
            - elasticsearch
            - file
            - googlecloud
            - googlecloudpubsub
            - googlemanagedprometheus
            - honeycombmarker
            - influxdb
            - kafka
            - loadbalancing
            - logicmonitor
            - logzio
            - mezmo
            - nop
            - opencensus
            - opensearch
            - otelarrow
            - otlp
            - otlphttp
            - prometheus
            - prometheusremotewrite
            - pulsar
            - rabbitmq
            - sapm
            - sentry
            - signalfx
            - splunk_hec
            - sumologic
            - syslog
            - tencentcloud_logservice
            - zipkin
        extensions:
            - ack
            - asapclient
            - awsproxy
            - basicauth
            - bearertokenauth
            - db_storage
            - docker_observer
            - ecs_observer
            - ecs_task_observer
            - file_storage
            - googleclientauth
            - headers_setter
            - health_check
            - host_observer
            - http_forwarder
            - jaeger_encoding
            - jaegerremotesampling
            - json_log_encoding
            - k8s_observer
            - oauth2client
            - oidc
            - opamp
            - otlp_encoding
            - pprof
            - redis_storage
            - sigv4auth
            - sumologic
            - zipkin_encoding
            - zpages
        processors:
            - attributes
            - batch
            - cumulativetodelta
            - deltatocumulative
            - deltatorate
            - filter
            - geoip
            - groupbyattrs
            - groupbytrace
            - interval
            - k8sattributes
            - logdedup
            - memory_limiter
            - metricsgeneration
            - metricstransform
            - probabilistic_sampler
            - redaction
            - remotetap
            - resource
            - resourcedetection
            - span
            - sumologic
            - tail_sampling
            - transform
        receivers:
            - active_directory_ds
            - aerospike
            - apache
            - apachespark
            - awscloudwatch
            - awscontainerinsightreceiver
            - awsecscontainermetrics
            - awsfirehose
            - awss3
            - awsxray
            - azureblob
            - azureeventhub
            - azuremonitor
            - bigip
            - carbon
            - chrony
            - cloudflare
            - cloudfoundry
            - collectd
            - couchdb
            - datadog
            - docker_stats
            - elasticsearch
            - envoyals
            - expvar
            - filelog
            - filestats
            - flinkmetrics
            - fluentforward
            - github
            - googlecloudmonitoring
            - googlecloudpubsub
            - googlecloudspanner
            - haproxy
            - hostmetrics
            - httpcheck
            - iis
            - influxdb
            - jaeger
            - jmx
            - journald
            - k8s_cluster
            - k8s_events
            - k8sobjects
            - kafka
            - kafkametrics
            - kubeletstats
            - libhoney
            - loki
            - memcached
            - mongodb
            - mongodbatlas
            - mysql
            - namedpipe
            - netflow
            - nginx
            - nop
            - nsxt
            - ntp
            - opencensus
            - oracledb
            - otelarrow
            - otlp
            - otlpjsonfile
            - podman_stats
            - postgresql
            - prometheus
            - prometheus_simple
            - pulsar
            - purefa
            - purefb
            - rabbitmq
            - receiver_creator
            - redis
            - riak
            - sapm
            - signalfx
            - skywalking
            - snmp
            - snowflake
            - solace
            - splunk_hec
            - splunkenterprise
            - sqlquery
            - sqlserver
            - sshcheck
            - statsd
            - syslog
            - tcplog
            - udplog
            - vcenter
            - wavefront
            - webhookevent
            - windowseventlog
            - windowsperfcounters
            - zipkin
            - zookeeper
    version: 0.122.0
status:
    conditions: null
