apiVersion: v1
kind: RemoteConfigSchema
metadata:
    attributes: null
    createdAt: null
    name: otelcol-0.156.0
    namespace: default
spec:
    binary: otelcol
    components:
        connectors:
            - forward
        exporters:
            - debug
            - file
            - kafka
            - nop
            - otlp_grpc
            - otlp_http
            - prometheus
            - prometheus_remote_write
            - zipkin
        extensions:
            - health_check
            - pprof
            - zpages
        processors:
            - attributes
            - batch
            - filter
            - memory_limiter
            - probabilistic_sampler
            - resource
            - span
        receivers:
            - host_metrics
            - jaeger
            - kafka
            - nop
            - otlp
            - prometheus
            - zipkin
    version: 0.156.0
status:
    conditions: null
