apiVersion: v1
kind: RemoteConfigSchema
metadata:
    attributes: null
    createdAt: null
    name: otelcol-contrib-0.88.0
    namespace: default
spec:
    binary: otelcol-contrib
    components:
        connectors:
            - count
            - datadog
            - forward
            - routing
            - servicegraph
            - spanmetrics
        exporters:
            - alibabacloud_logservice
            - awscloudwatchlogs
            - awsemf
            - awskinesis
            - awss3
            - awsxray
            - azuredataexplorer
            - azuremonitor
            - carbon
            - cassandra
            - clickhouse
            - coralogix
            - datadog
            - dataset
            - debug
            - dynatrace
            - elasticsearch
            - f5cloud
            - file
            - googlecloud
            - googlecloudpubsub
            - googlemanagedprometheus
            - influxdb
            - instana
            - kafka
            - loadbalancing
            - logging
            - logicmonitor
            - logzio
            - loki
            - mezmo
            - opencensus
            - otlp
            - otlphttp
            - prometheus
            - prometheusremotewrite
            - pulsar
            - sapm
            - sentry
            - signalfx
            - skywalking
            - splunk_hec
            - sumologic
            - tanzuobservability
            - tencentcloud_logservice
            - zipkin
        extensions:
            - asapclient
            - awsproxy
            - basicauth
            - bearertokenauth
            - db_storage
            - docker_observer
            - ecs_observer
            - ecs_task_observer
            - file_storage
            - headers_setter
            - health_check
            - host_observer
            - http_forwarder
            - jaegerremotesampling
            - k8s_observer
            - memory_ballast
            - oauth2client
            - oidc
            - pprof
            - sigv4auth
            - zpages
        processors:
            - attributes
            - batch
            - cumulativetodelta
            - datadog
            - deltatorate
            - experimental_metricsgeneration
            - filter
            - groupbyattrs
            - groupbytrace
            - k8sattributes
            - memory_limiter
            - metricstransform
            - probabilistic_sampler
            - redaction
            - remoteobserver
            - resource
            - resourcedetection
            - routing
            - servicegraph
            - span
            - spanmetrics
            - tail_sampling
            - transform
        receivers:
            - active_directory_ds
            - aerospike
            - apache
            - apachespark
            - awscloudwatch
            - awscontainerinsightreceiver
            - awsecscontainermetrics
            - awsfirehose
            - awsxray
            - azureblob
            - azureeventhub
            - azuremonitor
            - bigip
            - carbon
            - chrony
            - cloudflare
            - cloudfoundry
            - collectd
            - couchdb
            - datadog
            - docker_stats
            - elasticsearch
            - expvar
            - file
            - filelog
            - filestats
            - flinkmetrics
            - fluentforward
            - googlecloudpubsub
            - googlecloudspanner
            - haproxy
            - hostmetrics
            - httpcheck
            - iis
            - influxdb
            - jaeger
            - jmx
            - journald
            - k8s_cluster
            - k8s_events
            - k8sobjects
            - kafka
            - kafkametrics
            - kubeletstats
            - loki
            - memcached
            - mongodb
            - mongodbatlas
            - mysql
            - nginx
            - nsxt
            - opencensus
            - oracledb
            - otlp
            - otlpjsonfile
            - podman_stats
            - postgresql
            - prometheus
            - prometheus_simple
            - pulsar
            - purefa
            - purefb
            - rabbitmq
            - receiver_creator
            - redis
            - riak
            - sapm
            - signalfx
            - skywalking
            - snmp
            - snowflake
            - solace
            - splunk_hec
            - sqlquery
            - sqlserver
            - sshcheck
            - statsd
            - syslog
            - tcplog
            - udplog
            - vcenter
            - wavefront
            - webhookevent
            - windowseventlog
            - windowsperfcounters
            - zipkin
            - zookeeper
    version: 0.88.0
status:
    conditions: null
