apiVersion: v1
kind: RemoteConfigSchema
metadata:
    attributes: null
    createdAt: null
    name: otelcol-contrib-0.146.1
    namespace: default
spec:
    binary: otelcol-contrib
    components:
        connectors:
            - count
            - datadog
            - exceptions
            - failover
            - forward
            - grafanacloud
            - otlpjson
            - roundrobin
            - routing
            - servicegraph
            - spanmetrics
            - sum
        exporters:
            - alibabacloud_logservice
            - awscloudwatchlogs
            - awsemf
            - awskinesis
            - awss3
            - awsxray
            - azureblob
            - azuredataexplorer
            - azuremonitor
            - bmchelix
            - cassandra
            - clickhouse
            - coralogix
            - datadog
            - dataset
            - debug
            - doris
            - elasticsearch
            - faro
            - file
            - googlecloud
            - googlecloudpubsub
            - googlecloudstorage
            - googlemanagedprometheus
            - honeycombmarker
            - influxdb
            - kafka
            - loadbalancing
            - logicmonitor
            - logzio
            - mezmo
            - nop
            - opensearch
            - otelarrow
            - prometheus
            - prometheusremotewrite
            - pulsar
            - rabbitmq
            - sapm
            - sentry
            - signalfx
            - splunk_hec
            - stef
            - sumologic
            - syslog
            - tencentcloud_logservice
            - tinybird
            - zipkin
        extensions:
            - ack
            - asapclient
            - awscloudwatchmetricstreams_encoding
            - awslogs_encoding
            - awsproxy
            - azureauth
            - basicauth
            - bearertokenauth
            - cgroupruntime
            - datadog
            - db_storage
            - docker_observer
            - ecs_observer
            - file_storage
            - googleclientauth
            - googlecloudlogentry_encoding
            - headers_setter
            - health_check
            - host_observer
            - http_forwarder
            - jaeger_encoding
            - jaegerremotesampling
            - json_log_encoding
            - k8s_leader_elector
            - k8s_observer
            - kafkatopics_observer
            - oauth2client
            - oidc
            - opamp
            - otlp_encoding
            - pprof
            - redis_storage
            - sigv4auth
            - skywalking_encoding
            - sumologic
            - text_encoding
            - zipkin_encoding
            - zpages
        processors:
            - attributes
            - batch
            - coralogix
            - cumulativetodelta
            - deltatocumulative
            - deltatorate
            - filter
            - geoip
            - groupbyattrs
            - groupbytrace
            - interval
            - isolationforest
            - logdedup
            - memory_limiter
            - metricsgeneration
            - metricstarttime
            - metricstransform
            - probabilistic_sampler
            - redaction
            - remotetap
            - resource
            - resourcedetection
            - schema
            - span
            - sumologic
            - tail_sampling
            - transform
            - unroll
        receivers:
            - active_directory_ds
            - aerospike
            - apache
            - apachespark
            - awscloudwatch
            - awscontainerinsightreceiver
            - awsecscontainermetrics
            - awsfirehose
            - awss3
            - awsxray
            - azureblob
            - azuremonitor
            - carbon
            - chrony
            - cloudflare
            - cloudfoundry
            - collectd
            - couchdb
            - datadog
            - docker_stats
            - elasticsearch
            - envoyals
            - expvar
            - faro
            - filelog
            - filestats
            - flinkmetrics
            - fluentforward
            - github
            - gitlab
            - googlecloudmonitoring
            - googlecloudpubsub
            - googlecloudspanner
            - haproxy
            - hostmetrics
            - httpcheck
            - iis
            - influxdb
            - jaeger
            - jmx
            - journald
            - k8s_cluster
            - k8s_events
            - k8sobjects
            - kafka
            - kafkametrics
            - kubeletstats
            - libhoney
            - loki
            - macosunifiedlogging
            - memcached
            - mongodb
            - mysql
            - namedpipe
            - netflow
            - nginx
            - nop
            - nsxt
            - ntp
            - oracledb
            - otelarrow
            - otlp
            - otlpjsonfile
            - podman_stats
            - postgresql
            - prometheus
            - prometheus_simple
            - prometheusremotewrite
            - pulsar
            - purefa
            - purefb
            - rabbitmq
            - receiver_creator
            - redis
            - riak
            - saphana
            - signalfx
            - skywalking
            - snmp
            - snowflake
            - solace
            - splunk_hec
            - splunkenterprise
            - sqlquery
            - sqlserver
            - sshcheck
            - statsd
            - stef
            - syslog
            - systemd
            - tcpcheck
            - tcplog
            - tlscheck
            - udplog
            - vcenter
            - wavefront
            - webhookevent
            - windowseventlog
            - windowsperfcounters
            - yanggrpc
            - zipkin
            - zookeeper
    version: 0.146.1
status:
    conditions: null
