// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/pkg/apiserver/application/port"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManageUsecase creates a new instance of MockManageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManageUsecase {
	mock := &MockManageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManageUsecase is an autogenerated mock type for the ManageUsecase type
type MockManageUsecase struct {
	mock.Mock
}

type MockManageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManageUsecase) EXPECT() *MockManageUsecase_Expecter {
	return &MockManageUsecase_Expecter{mock: &_m.Mock}
}

// GetApplication provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) GetApplication(ctx context.Context, id string) (*v1.Application, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplication")
	}

	var r0 *v1.Application
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.Application, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.Application); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Application)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_GetApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplication'
type MockManageUsecase_GetApplication_Call struct {
	*mock.Call
}

// GetApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockManageUsecase_Expecter) GetApplication(ctx interface{}, id interface{}) *MockManageUsecase_GetApplication_Call {
	return &MockManageUsecase_GetApplication_Call{Call: _e.mock.On("GetApplication", ctx, id)}
}

func (_c *MockManageUsecase_GetApplication_Call) Run(run func(ctx context.Context, id string)) *MockManageUsecase_GetApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_GetApplication_Call) Return(application *v1.Application, err error) *MockManageUsecase_GetApplication_Call {
	_c.Call.Return(application, err)
	return _c
}

func (_c *MockManageUsecase_GetApplication_Call) RunAndReturn(run func(ctx context.Context, id string) (*v1.Application, error)) *MockManageUsecase_GetApplication_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentsByApplication provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListAgentsByApplication(ctx context.Context, id string, options *port.ListOptions) (*v1.ListResponse[v1.Agent], error) {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentsByApplication")
	}

	var r0 *v1.ListResponse[v1.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *port.ListOptions) (*v1.ListResponse[v1.Agent], error)); ok {
		return returnFunc(ctx, id, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *port.ListOptions) *v1.ListResponse[v1.Agent]); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *port.ListOptions) error); ok {
		r1 = returnFunc(ctx, id, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListAgentsByApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentsByApplication'
type MockManageUsecase_ListAgentsByApplication_Call struct {
	*mock.Call
}

// ListAgentsByApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options *port.ListOptions
func (_e *MockManageUsecase_Expecter) ListAgentsByApplication(ctx interface{}, id interface{}, options interface{}) *MockManageUsecase_ListAgentsByApplication_Call {
	return &MockManageUsecase_ListAgentsByApplication_Call{Call: _e.mock.On("ListAgentsByApplication", ctx, id, options)}
}

func (_c *MockManageUsecase_ListAgentsByApplication_Call) Run(run func(ctx context.Context, id string, options *port.ListOptions)) *MockManageUsecase_ListAgentsByApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *port.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*port.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListAgentsByApplication_Call) Return(listResponse *v1.ListResponse[v1.Agent], err error) *MockManageUsecase_ListAgentsByApplication_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListAgentsByApplication_Call) RunAndReturn(run func(ctx context.Context, id string, options *port.ListOptions) (*v1.ListResponse[v1.Agent], error)) *MockManageUsecase_ListAgentsByApplication_Call {
	_c.Call.Return(run)
	return _c
}

// ListApplications provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListApplications(ctx context.Context, options *port.ListOptions) (*v1.ListResponse[v1.Application], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListApplications")
	}

	var r0 *v1.ListResponse[v1.Application]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *port.ListOptions) (*v1.ListResponse[v1.Application], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *port.ListOptions) *v1.ListResponse[v1.Application]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Application])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *port.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListApplications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListApplications'
type MockManageUsecase_ListApplications_Call struct {
	*mock.Call
}

// ListApplications is a helper method to define mock.On call
//   - ctx context.Context
//   - options *port.ListOptions
func (_e *MockManageUsecase_Expecter) ListApplications(ctx interface{}, options interface{}) *MockManageUsecase_ListApplications_Call {
	return &MockManageUsecase_ListApplications_Call{Call: _e.mock.On("ListApplications", ctx, options)}
}

func (_c *MockManageUsecase_ListApplications_Call) Run(run func(ctx context.Context, options *port.ListOptions)) *MockManageUsecase_ListApplications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *port.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*port.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListApplications_Call) Return(listResponse *v1.ListResponse[v1.Application], err error) *MockManageUsecase_ListApplications_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListApplications_Call) RunAndReturn(run func(ctx context.Context, options *port.ListOptions) (*v1.ListResponse[v1.Application], error)) *MockManageUsecase_ListApplications_Call {
	_c.Call.Return(run)
	return _c
}
