---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: opampcommander
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
      - name: apiserver
        image: minukdev/opampcommander:0.1.0
        command:
        - /apiserver
        - --db-host=etcd.opampcommander.svc.cluster.local.:2379
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: opampcommander
  labels:
    app: apiserver
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: apiserver
  type: ClusterIP
