// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasemock

import (
	"context"

	"github.com/minuk-dev/opampcommander/api/v1"
	"github.com/minuk-dev/opampcommander/pkg/apiserver/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManageUsecase creates a new instance of MockManageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManageUsecase {
	mock := &MockManageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManageUsecase is an autogenerated mock type for the ManageUsecase type
type MockManageUsecase struct {
	mock.Mock
}

type MockManageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManageUsecase) EXPECT() *MockManageUsecase_Expecter {
	return &MockManageUsecase_Expecter{mock: &_m.Mock}
}

// GetHost provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) GetHost(ctx context.Context, id string) (*v1.Host, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetHost")
	}

	var r0 *v1.Host
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v1.Host, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v1.Host); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Host)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_GetHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHost'
type MockManageUsecase_GetHost_Call struct {
	*mock.Call
}

// GetHost is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockManageUsecase_Expecter) GetHost(ctx interface{}, id interface{}) *MockManageUsecase_GetHost_Call {
	return &MockManageUsecase_GetHost_Call{Call: _e.mock.On("GetHost", ctx, id)}
}

func (_c *MockManageUsecase_GetHost_Call) Run(run func(ctx context.Context, id string)) *MockManageUsecase_GetHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_GetHost_Call) Return(host *v1.Host, err error) *MockManageUsecase_GetHost_Call {
	_c.Call.Return(host, err)
	return _c
}

func (_c *MockManageUsecase_GetHost_Call) RunAndReturn(run func(ctx context.Context, id string) (*v1.Host, error)) *MockManageUsecase_GetHost_Call {
	_c.Call.Return(run)
	return _c
}

// ListAgentsByHost provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListAgentsByHost(ctx context.Context, id string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error) {
	ret := _mock.Called(ctx, id, options)

	if len(ret) == 0 {
		panic("no return value specified for ListAgentsByHost")
	}

	var r0 *v1.ListResponse[v1.Agent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) (*v1.ListResponse[v1.Agent], error)); ok {
		return returnFunc(ctx, id, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *model.ListOptions) *v1.ListResponse[v1.Agent]); ok {
		r0 = returnFunc(ctx, id, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Agent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, id, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListAgentsByHost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAgentsByHost'
type MockManageUsecase_ListAgentsByHost_Call struct {
	*mock.Call
}

// ListAgentsByHost is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListAgentsByHost(ctx interface{}, id interface{}, options interface{}) *MockManageUsecase_ListAgentsByHost_Call {
	return &MockManageUsecase_ListAgentsByHost_Call{Call: _e.mock.On("ListAgentsByHost", ctx, id, options)}
}

func (_c *MockManageUsecase_ListAgentsByHost_Call) Run(run func(ctx context.Context, id string, options *model.ListOptions)) *MockManageUsecase_ListAgentsByHost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *model.ListOptions
		if args[2] != nil {
			arg2 = args[2].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListAgentsByHost_Call) Return(listResponse *v1.ListResponse[v1.Agent], err error) *MockManageUsecase_ListAgentsByHost_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListAgentsByHost_Call) RunAndReturn(run func(ctx context.Context, id string, options *model.ListOptions) (*v1.ListResponse[v1.Agent], error)) *MockManageUsecase_ListAgentsByHost_Call {
	_c.Call.Return(run)
	return _c
}

// ListHosts provides a mock function for the type MockManageUsecase
func (_mock *MockManageUsecase) ListHosts(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Host], error) {
	ret := _mock.Called(ctx, options)

	if len(ret) == 0 {
		panic("no return value specified for ListHosts")
	}

	var r0 *v1.ListResponse[v1.Host]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) (*v1.ListResponse[v1.Host], error)); ok {
		return returnFunc(ctx, options)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.ListOptions) *v1.ListResponse[v1.Host]); ok {
		r0 = returnFunc(ctx, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ListResponse[v1.Host])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.ListOptions) error); ok {
		r1 = returnFunc(ctx, options)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManageUsecase_ListHosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHosts'
type MockManageUsecase_ListHosts_Call struct {
	*mock.Call
}

// ListHosts is a helper method to define mock.On call
//   - ctx context.Context
//   - options *model.ListOptions
func (_e *MockManageUsecase_Expecter) ListHosts(ctx interface{}, options interface{}) *MockManageUsecase_ListHosts_Call {
	return &MockManageUsecase_ListHosts_Call{Call: _e.mock.On("ListHosts", ctx, options)}
}

func (_c *MockManageUsecase_ListHosts_Call) Run(run func(ctx context.Context, options *model.ListOptions)) *MockManageUsecase_ListHosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.ListOptions
		if args[1] != nil {
			arg1 = args[1].(*model.ListOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManageUsecase_ListHosts_Call) Return(listResponse *v1.ListResponse[v1.Host], err error) *MockManageUsecase_ListHosts_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockManageUsecase_ListHosts_Call) RunAndReturn(run func(ctx context.Context, options *model.ListOptions) (*v1.ListResponse[v1.Host], error)) *MockManageUsecase_ListHosts_Call {
	_c.Call.Return(run)
	return _c
}
