// Package api contains API models and definitions.
package api

// ErrorModel represents a standardized error response model.
// RFC 9457 Problem Details for HTTP APIs.
type ErrorModel struct {
	// Type is a URI reference that identifies the problem type.
	// example: "https://example.com/probs/out-of-credit"
	Type string `json:"type,omitempty"`

	// Title is a short, human-readable summary of the problem type.
	// example: "Bad Request"
	Title string `json:"title,omitempty"`

	// Status is the HTTP status code generated by the origin server for this occurrence of the problem.
	// example: 400
	Status int `json:"status,omitempty"`

	// Detail is a human-readable explanation specific to this occurrence of the problem.
	// example: "Your request parameters didn't validate."
	Detail string `json:"detail,omitempty"`

	// Instance is a URI reference that identifies the specific occurrence of the problem.
	Instance string `json:"instance,omitempty"`

	// Errors provides additional error details.
	Errors []*ErrorDetail `json:"errors,omitempty"`
} // @name ErrorModel

// ErrorDetail represents a single error detail in the error response model.
type ErrorDetail struct {
	Message  string `json:"message,omitempty"`
	Location string `json:"location,omitempty"`
	Value    any    `json:"value,omitempty"`
} // @name ErrorDetail
